# Modules update
## Notebook to update current just-dna-seq modules

In [ ]:
import polars as pl
import polars_bio as pb
import sqlite3
from pathlib import Path
from pycomfort import files

from platformdirs import user_cache_dir

# Configure Polars to show more rows and columns
pl.Config.set_tbl_rows(-1)  # Show all rows
pl.Config.set_tbl_cols(-1)  # Show all columns
pl.Config.set_tbl_width_chars(1000)  # Increase table width
pl.Config.set_fmt_str_lengths(1000)  # Show longer string values without truncation

polars.config.Config

In [7]:
from os import listdir
from prepare_annotations.cli import dbsnp_t2t
from prepare_annotations.resources import get_cache_dir
cache = get_cache_dir()
ensembl_cache = cache / "ensembl" / "homo_sapiens" 
clinvar_cache = cache / "clinvar"
dbsnp_t2t_cache = cache / "db"
listdir(ensembl_cache)

['homo_sapiens-chr2.parquet',
 'homo_sapiens-chr9.parquet',
 'homo_sapiens-chr17.parquet',
 'homo_sapiens-chr21.parquet',
 'homo_sapiens-chr8.parquet',
 'homo_sapiens-chrY.parquet',
 'homo_sapiens-chr20.parquet',
 'homo_sapiens-chr19.parquet',
 'homo_sapiens-chr4.parquet',
 'homo_sapiens-chr14.parquet',
 'homo_sapiens-chr3.parquet',
 'homo_sapiens-chr13.parquet',
 'homo_sapiens-chrX.parquet',
 'homo_sapiens-chr6.parquet',
 'homo_sapiens-chr5.parquet',
 'homo_sapiens-chr22.parquet',
 'homo_sapiens-chr1.parquet',
 'homo_sapiens-chrMT.parquet',
 'vcf',
 'homo_sapiens-chr15.parquet',
 'homo_sapiens-chr16.parquet',
 'homo_sapiens-chr7.parquet',
 'homo_sapiens-chr12.parquet',
 'homo_sapiens-chr18.parquet',
 'homo_sapiens-chr11.parquet',
 'homo_sapiens-chr10.parquet']

In [8]:
from pycomfort.files import tprint
tprint(clinvar_cache)

clinvar
	clinvar_20260104_VEP.parquet
	vcf
		clinvar_20260104_VEP.vcf
		clinvar_20260104_VEP.vcf.gz
		.fsspec_cache

In [9]:
clinvar = pl.scan_parquet(clinvar_cache / "clinvar_20260104_VEP.parquet")
clinvar.head(5).collect()

shape: (5, 50)
┌───────┬───────┬───────┬─────────┬─────┬─────┬───────────┬──────┬────────┬────────┬─────────┬────────┬──────────┬──────────────────────────┬───────────┬──────────────────────────────────────────────────────────────────────────────────┬──────────────┬─────────────────────────────┬────────────────────────────────────────────┬────────────────────────────┬────────────┬────────────┬──────────────────┬───────────────────────────┬────────────┬─────────────────────────┬───────────┬─────────────┬─────────────────────────────────┬───────────┬───────────┬───────────┬──────────────┬───────────┬───────────┬────────────┬───────────┬───────────┬───────────┬────────────────┬───────────┬───────────┬───────────┬──────────────┬────────────┬───────────┬───────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────┐
│ chrom ┆ start ┆ end   ┆ id      ┆ ref ┆ alt ┆ alts      ┆ qual ┆ filter ┆ AF_ESP ┆ AF_EXAC ┆ AF_TGP ┆ ALLELEID ┆ CLNDN                    ┆ CLNDNINCL ┆ CLNDISDB                                                                         ┆ CLNDISDBINCL ┆ CLNHGVS                     ┆ CLNREVSTAT                                 ┆ CLNSIG                     ┆ CLNSIGCONF ┆ CLNSIGINCL ┆ CLNSIGSCV        ┆ CLNVC                     ┆ CLNVCSO    ┆ CLNVI                   ┆ DBVARID   ┆ GENEINFO    ┆ MC                              ┆ ONCDN     ┆ ONCDNINCL ┆ ONCDISDB  ┆ ONCDISDBINCL ┆ ONC       ┆ ONCINCL   ┆ ONCREVSTAT ┆ ONCSCV    ┆ ONCCONF   ┆ ORIGIN    ┆ RS             ┆ SCIDN     ┆ SCIDNINCL ┆ SCIDISDB  ┆ SCIDISDBINCL ┆ SCIREVSTAT ┆ SCI       ┆ SCIINCL   ┆ SCISCV    ┆ CSQ                                                                                                                                                                                                                    ┆ phlyoP100way │
│ ---   ┆ ---   ┆ ---   ┆ ---     ┆ --- ┆ --- ┆ ---       ┆ ---  ┆ ---    ┆ ---    ┆ ---     ┆ ---    ┆ ---      ┆ ---                      ┆ ---       ┆ ---                                                                              ┆ ---          ┆ ---                         ┆ ---                                        ┆ ---                        ┆ ---        ┆ ---        ┆ ---              ┆ ---                       ┆ ---        ┆ ---                     ┆ ---       ┆ ---         ┆ ---                             ┆ ---       ┆ ---       ┆ ---       ┆ ---          ┆ ---       ┆ ---       ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---            ┆ ---       ┆ ---       ┆ ---       ┆ ---          ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---                                                                                                                                                                                                                    ┆ ---          │
│ str   ┆ u32   ┆ u32   ┆ str     ┆ str ┆ str ┆ list[str] ┆ f64  ┆ str    ┆ f32    ┆ f32     ┆ f32    ┆ i32      ┆ list[str]                ┆ list[str] ┆ list[str]                                                                        ┆ list[str]    ┆ list[str]                   ┆ list[str]                                  ┆ list[str]                  ┆ list[str]  ┆ list[str]  ┆ list[str]        ┆ str                       ┆ str        ┆ list[str]               ┆ list[str] ┆ str         ┆ list[str]                       ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]    ┆ list[str] ┆ list[str] ┆ list[str]  ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]      ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]    ┆ list[str]  ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]                                                                                                                                                                                                              ┆ list[str]    │
╞═══════╪═══════╪═══════╪═════════╪═════╪═════╪═══════════╪══════╪════════╪════════╪═════════╪════════╪══════════╪══════════════════════════╪═══════════╪══════════════════════════════════════════════════════════════════════════════════╪══════════════╪═════════════════════════════╪════════════════════════════════════════════╪════════════════════════════╪════════════╪════════════╪══════════════════╪═══════════════════════════╪════════════╪═════════════════════════╪═══════════╪═════════════╪═════════════════════════════════╪═══════════╪═══════════╪═══════════╪══════════════╪═══════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪════════════════╪═══════════╪═══════════╪═══════════╪══════════════╪════════════╪═══════════╪═══════════╪═══════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════╡
│ 1     ┆ 66926 ┆ 66927 ┆ 3385321 ┆ AG  ┆ A   ┆ ["A"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 3544463  ┆ ["Retinitis_pigmentosa"] ┆ null      ┆ ["Human_Phenotype_Ontology:HP:0000547", "MONDO:MONDO:0019200", … "Orphanet:791"] ┆ null         ┆ ["NC_000001.11:g.66927del"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV005419006"] ┆ Deletion                  ┆ SO:0000159 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001627|intron_variant"]   ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["0"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["-|downstream_gene_variant|MODIFIER|OR4G11P|ENSG00000240361|Transcript|ENST00000492842.2|transcribed_unprocessed_pseudogene|||||||||||3040|1||deletion|1:66926:G:|HGNC|HGNC:31276|||||||||||||||||||||||||||||||g|||| ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 0.143999993801117", "-|intron_variant|MODIFIER|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding||2/2|ENST00000641515.2:c.9+1354del|||||||||1||deletion|1:66926:G:|HGNC|HGNC:14825|ENSP00000493376|||| ┆              │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ ||||||||||||||||||||||||||g||||0.143999993801117", …                                                                                                                                                                   ┆              │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ "-|downstream_gene_variant|MODIFIER||ENSG00000290826|Transcript|ENST00000832531.1|lncRNA|||||||||||3401|1||deletion|1:66926:G:|||||||||||||||||||||||||||||||||g||||0.143999993801117"]                                ┆              │
│ 1     ┆ 69134 ┆ 69134 ┆ 2205837 ┆ A   ┆ G   ┆ ["G"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 2193183  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69134A>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Likely_benign"]          ┆ null       ┆ null       ┆ ["SCV003526545"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ ["ClinGen:CA502008"]    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ ["781394307"]  ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.107A>G|ENSP00000493376.2:p.Glu36Gly|167|107|36|E/G|gAa/gGa|rs781394307||1||SNV|1:69133:A:G|HG ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ NC|HGNC:14825|ENSP00000493376||tolerated(0.08)|benign(0.007)||likely_benign||1||ClinVar::RCV002668554&VCV002205837&RCV004071174||||||16.64|1.975028||45|-1|-19|-1|0.00|0.00|0.02|0.00|OR4F5||||N||||0.405000001192093" ┆              │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ ]                                                                                                                                                                                                                      ┆              │
│ 1     ┆ 69308 ┆ 69308 ┆ 3925305 ┆ A   ┆ G   ┆ ["G"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 4039319  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69308A>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV006120601"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.281A>G|ENSP00000493376.2:p.Lys94Arg|341|281|94|K/R|aAg/aGg|||1||SNV|1:69307:A:G|HGNC|HGNC:148 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 25|ENSP00000493376||deleterious(0.02)|benign(0.093)||||||||||||18.76|2.446142||-12|26|1|31|0.01|0.00|0.00|0.00|OR4F5||||a||||1.42999994754791"]                                                                        ┆              │
│ 1     ┆ 69314 ┆ 69314 ┆ 3205580 ┆ T   ┆ G   ┆ ["G"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 3374047  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69314T>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV004995495"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ ["ClinGen:CA338197388"] ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ ["2521653848"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.287T>G|ENSP00000493376.2:p.Ile96Ser|347|287|96|I/S|aTt/aGt|||1||SNV|1:69313:T:G|HGNC|HGNC:148 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 25|ENSP00000493376||deleterious(0)|possibly_damaging(0.652)||||||||||||22.7|3.512588||-12|-18|-1|25|0.00|0.00|0.04|0.00|OR4F5||||t||||4.60900020599365"]                                                               ┆              │
│ 1     ┆ 69404 ┆ 69404 ┆ 3925306 ┆ T   ┆ C   ┆ ["C"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 4039320  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69404T>C"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV006120602"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["C|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.377T>C|ENSP00000493376.2:p.Met126Thr|437|377|126|M/T|aTg/aCg|rs1328728149||1||SNV|1:69403:T:C ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ |HGNC|HGNC:14825|ENSP00000493376||deleterious(0)|benign(0.07)||||||||||||19.11|2.526974||-34|-49|1|-13|0.00|0.00|0.00|0.00|OR4F5||||t||||0.241999998688698"]                                                           ┆              │
└───────┴───────┴───────┴─────────┴─────┴─────┴───────────┴──────┴────────┴────────┴─────────┴────────┴──────────┴──────────────────────────┴───────────┴──────────────────────────────────────────────────────────────────────────────────┴──────────────┴─────────────────────────────┴────────────────────────────────────────────┴────────────────────────────┴────────────┴────────────┴──────────────────┴───────────────────────────┴────────────┴─────────────────────────┴───────────┴─────────────┴─────────────────────────────────┴───────────┴───────────┴───────────┴──────────────┴───────────┴───────────┴────────────┴───────────┴───────────┴───────────┴────────────────┴───────────┴───────────┴───────────┴──────────────┴────────────┴───────────┴───────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────┘

In [10]:
from pycomfort.files import tprint
clinvar_cache = cache / "clinvar"
tprint(cache, depth=1)

just-dna-pipelines
	dbsnp_grch38
		vcf
			GCF_000001405.40.gz
			.fsspec_cache
	clinvar
		clinvar_20260104_VEP.parquet
		vcf
			clinvar_20260104_VEP.vcf
			clinvar_20260104_VEP.vcf.gz
			.fsspec_cache
	dbsnp_t2t
		vcf
			chm13v2.0_dbSNPv155.vcf.gz
			chm13v2.0_dbSNPv155.vcf.gz.tbi
			.fsspec_cache
	.fsspec_cache
		20f9321d22b6bf386b0a23d2499243e195aff8e21d1654a53c0da8019c8a8b7a
		0416f6134bd5c84286ebd4fffe845a4d6768e6f86f069a0773eff784aa4c084d
		765b8fa0647d27df66fbfa8c859f77d0c565bbb9e7ab15760b7e0e0e84a59638
		dca203f561595c9b659bd8b85a57c4b23e1ff6d02bced4cdc786b77fd31c299c
		2e23a05fd1d65acd59d1d9342e201e0f96aef41d030ba274858a733a3b89af45
		955092064d2abb285773b06afeba9f4c5433ef6c7e44d484c8a2d8ec76f5a89c
		8b12c9270181eff64730438982c27e1abf94bc8cc306d81afecba3bcdb3f2756
		b29bc733eeeefd2f16b04d3b2b388f708d012d2da8b2e8548843c1a7fe09e6dd
		3e6b27d87ef73d02741a7a31dfadc5500c625cf849e15b27fb2eddf0e593a4d7
		a98b26f48b8ae5cff08d83198727e25ddf71e9f74999d8b7cc68ae23fad793d1
		b6f04df9d2463af48af3ed7a076f31c747bfb76d926eea0e99f8e5fb99aee2de
		c1532e95aff03762d0f1d262033880a9a0ee5dbf0ab5fbbeab59739f82bebc06
		a1e660f1b6f8881723856fb15da4edc90431fc4da7788f10ace8a998b8c4f1df
		5fc199031ab98e57f415aa9bcb5740eb7334ed7365a0da72e44ff8b124fc7449
		685a2f8f3e41bc3782d359c16431508be8430f9d9ecef023ac1df2ba34e5f9d7
		a70e19f5693abcbf0b72ea5af221c8a038655e4807b7b6810ad37a4764318df2
		5b966915ba0e3827996869f03b4618e6f278af900af91d8d70afcc571e725dcc
		26dfe358b5f64aea425b5338ae317d484e32f262a08112709364e693faacfff1
		c57b22848598d8852c32b677bc5e7a0f2e38f96b80ec6d21b53b14302f7d2bb7
		0c30a73e6f464f62a5ff04eaa5c4899b1bded084163bab70d7b28c538d478335
		1dd5263e68ef09c17aecad303b7d8b8c924590ad8fb0ed8a4eb0c40e9bad9ca8
		2491340ace46c4a9b3ab6b3d2b9a3132612aa4b5a226f527b2c5305ec4b103f5
		bdc6dfcff61193ed6c868d0c1c9f65df8668827d81fe16f335b0fdd4ef600a45
		97cf0fab0d97a98f4eec6c34a3b769ef5de682c5d20ab1654a01b8b0351f622b
		321ea42b5fb07231dd7c3c7ff22766ce79b484289982106002b426781268501b
		cache
		0833c226e7ce27f2dcfdf5fe14e82f0d4822548f10084d932a5174429ab32ebc
	ensembl
		homo_sapiens
			homo_sapiens-chr2.parquet
			homo_sapiens-chr9.parquet
			homo_sapiens-chr17.parquet
			homo_sapiens-chr21.parquet
			homo_sapiens-chr8.parquet
			homo_sapiens-chrY.parquet
			homo_sapiens-chr20.parquet
			homo_sapiens-chr19.parquet
			homo_sapiens-chr4.parquet
			homo_sapiens-chr14.parquet
			homo_sapiens-chr3.parquet
			homo_sapiens-chr13.parquet
			homo_sapiens-chrX.parquet
			homo_sapiens-chr6.parquet
			homo_sapiens-chr5.parquet
			homo_sapiens-chr22.parquet
			homo_sapiens-chr1.parquet
			homo_sapiens-chrMT.parquet
			homo_sapiens-chr15.parquet
			homo_sapiens-chr16.parquet
			homo_sapiens-chr7.parquet
			homo_sapiens-chr12.parquet
			homo_sapiens-chr18.parquet
			homo_sapiens-chr11.parquet
			homo_sapiens-chr10.parquet
			vcf
				homo_sapiens-chr1.vcf.gz
				homo_sapiens-chr5.vcf.gz
				homo_sapiens-chr6.vcf.gz
				homo_sapiens-chr9.vcf.gz
				homo_sapiens-chr10.vcf.gz
				homo_sapiens-chr21.vcf.gz
				homo_sapiens-chr4.vcf.gz
				homo_sapiens-chr17.vcf.gz
				homo_sapiens-chr14.vcf.gz
				homo_sapiens-chr2.vcf.gz
				homo_sapiens-chr19.vcf.gz
				homo_sapiens-chr22.vcf.gz
				homo_sapiens-chr8.vcf.gz
				homo_sapiens-chr20.vcf.gz
				homo_sapiens-chr16.vcf.gz
				homo_sapiens-chrX.vcf.gz
				homo_sapiens-chr7.vcf.gz
				homo_sapiens-chrY.vcf.gz
				homo_sapiens-chr15.vcf.gz
				homo_sapiens-chr11.vcf.gz
				homo_sapiens-chrMT.vcf.gz
				homo_sapiens-chr18.vcf.gz
				homo_sapiens-chr13.vcf.gz
				homo_sapiens-chr12.vcf.gz
				homo_sapiens-chr3.vcf.gz
				.fsspec_cache
	gnomad_v4
	repositories
		dna-seq_just_cancer
			README.md
			just_cancer.py
			just_cancer.yml
			LICENSE
			.gitignore
			logo.png
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-0500909bf2d473f1720465cda319c303f3c0f48e.pack
						pack-0500909bf2d473f1720465cda319c303f3c0f48e.idx
						pack-0500909bf2d473f1720465cda319c303f3c0f48e.rev
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				genes.txt
		dna-seq_just_longevitymap
			README.md
			just_longevitymap.yml
			LICENSE
			just_longevitymap.py
			.gitignore
			longevitymap_ref_homo.py
			logo.png
			.git
				index
				packed-refs
				config
				ORIG_HEAD
				HEAD
				FETCH_HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-8ade12ffac84cf98a244612e7889206a5bde498d.idx
						pack-8ade12ffac84cf98a244612e7889206a5bde498d.pack
						pack-8ade12ffac84cf98a244612e7889206a5bde498d.rev
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				longevitymap.sqlite
		dna-seq_just_drugs
			README.md
			LICENSE
			.gitignore
			just_drugs.yml
			just_drugs.py
			logo.png
			.git
				index
				packed-refs
				config
				ORIG_HEAD
				HEAD
				FETCH_HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-22d4d4512046f548c9bb9482cbe937e18257a66e.idx
						pack-22d4d4512046f548c9bb9482cbe937e18257a66e.rev
						pack-22d4d4512046f548c9bb9482cbe937e18257a66e.pack
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				annotation_tab.tsv
		dna-seq_just_lipidmetabolism
			README.md
			lipidmetabolism_ref_homo.py
			just_lipidmetabolism.yml
			just_lipidmetabolism.py
			LICENSE
			.gitignore
			logo.png
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							main
				objects
					info
					pack
						pack-fc3989f1a95cdd18d5fa44255b1d967185a2a9b7.rev
						pack-fc3989f1a95cdd18d5fa44255b1d967185a2a9b7.idx
						pack-fc3989f1a95cdd18d5fa44255b1d967185a2a9b7.pack
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						main
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				lipid_metabolism.sqlite
		dna-seq_just_coronary
			README.md
			coronary_ref_homo.py
			just_coronary.yml
			LICENSE
			.gitignore
			logo.png
			just_coronary.py
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-a83fac7f4c96743f73daade4847f683a1e0aa1a5.idx
						pack-a83fac7f4c96743f73daade4847f683a1e0aa1a5.pack
						pack-a83fac7f4c96743f73daade4847f683a1e0aa1a5.rev
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				coronary.sqlite
		dna-seq_just_prs
			README.md
			just_prs.py
			just_prs.yml
			LICENSE
			.gitignore
			logo.png
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-5edb96eb70549b0ea2fde09a8363cf4cea4d7016.idx
						pack-5edb96eb70549b0ea2fde09a8363cf4cea4d7016.rev
						pack-5edb96eb70549b0ea2fde09a8363cf4cea4d7016.pack
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				prs.sqlite
		dna-seq_just_superhuman
			README.md
			superhumansite.png
			just_superhuman.yml
			just_superhuman.py
			LICENSE
			.gitignore
			just_superhuman.md
			logo.png
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							main
				objects
					info
					pack
						pack-5a6b414fd07afc048c55da0c3e2c7f332ee4e3db.idx
						pack-5a6b414fd07afc048c55da0c3e2c7f332ee4e3db.rev
						pack-5a6b414fd07afc048c55da0c3e2c7f332ee4e3db.pack
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						main
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				superhuman.sqlite
			example
				antonkulaga.vcf.superhuman.html
		dna-seq_just_vo2max
			README.md
			vo2max_ref_homo.py
			just_vo2max.py
			LICENSE
			just_vo2max.yml
			.gitignore
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							main
				objects
					info
					pack
						pack-65f24937b7965fde615c13a6e17ce49231a1579a.idx
						pack-65f24937b7965fde615c13a6e17ce49231a1579a.pack
						pack-65f24937b7965fde615c13a6e17ce49231a1579a.rev
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						main
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				vo2max.sqlite

## Loading modules

In [11]:
from pycomfort import files
from pathlib import Path
base = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data = base / "data"
modules = data / "modules"
files.tprint(modules)

modules
	.gitignore
	just_drugs
		annotation_tab.tsv
	just_longevitymap
		longevitymap.sqlite
	just_coronary
		coronary.sqlite
	just_lipidmetabolism
		lipid_metabolism.sqlite
	just_vo2max
		vo2max.sqlite
	longevitymap_annotations.parquet
	just_superhuman
		superhuman.sqlite
	just_prs
		prs.sqlite
	just_cancer
		genes.txt

## Modules

In [12]:
import sqlite3
import polars as pl

def list_tables(conn: sqlite3.Connection):
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()
    return tables

def print_tables(conn: sqlite3.Connection):
    tables = list_tables(conn)
    cursor = conn.cursor()
    # Get schema for each table
    for table in tables:
        table_name = table[0]
        print(f"\nSchema for table '{table_name}':")
        cursor.execute(f"PRAGMA table_info({table_name});")
        columns = cursor.fetchall()
        for col in columns:
            print(f"  {col[1]} ({col[2]})")
    return tables

In [13]:
import sqlite3
import polars as pl

# Connect to the database
db_path = modules / "just_longevitymap" / "longevitymap.sqlite"
conn = sqlite3.connect(db_path)

list_tables(conn)

[('gene',),
 ('population',),
 ('variant',),
 ('allele_weights',),
 ('categories',)]

## Join with rsid

In [14]:
weights = pl.read_database("""
SELECT rsid, allele, state, zygosity, weight, priority, categories.name
FROM allele_weights, categories WHERE categories.id = allele_weights.category_id
""", connection=conn).lazy()
weights.head(5).collect(engine="streaming")

shape: (5, 7)
┌──────────┬────────┬───────┬──────────┬────────┬──────────┬────────┐
│ rsid     ┆ allele ┆ state ┆ zygosity ┆ weight ┆ priority ┆ name   │
│ ---      ┆ ---    ┆ ---   ┆ ---      ┆ ---    ┆ ---      ┆ ---    │
│ str      ┆ str    ┆ str   ┆ str      ┆ f64    ┆ str      ┆ str    │
╞══════════╪════════╪═══════╪══════════╪════════╪══════════╪════════╡
│ rs7412   ┆ T      ┆ alt   ┆ het      ┆ 0.5    ┆ 1.0      ┆ lipids │
│ rs7412   ┆ T      ┆ alt   ┆ hom      ┆ 1.0    ┆ 1.0      ┆ lipids │
│ rs429358 ┆ C      ┆ alt   ┆ het      ┆ -0.5   ┆ 1.0      ┆ lipids │
│ rs429358 ┆ C      ┆ alt   ┆ hom      ┆ -1.0   ┆ 1.0      ┆ lipids │
│ rs5882   ┆ G      ┆ ref   ┆ hom      ┆ 0.97   ┆ 0.97     ┆ lipids │
└──────────┴────────┴───────┴──────────┴────────┴──────────┴────────┘

In [15]:
variants = pl.read_database("""
SELECT variant.identifier as rsid, variant.study_design, variant.conclusions, variant.association, 
       variant.gender, variant.quickref, variant.quickyear, variant.quickpubmed, 
       population.name as population_name
FROM variant
JOIN population ON variant.population_id = population.id
""", connection=conn).with_columns(
    (pl.col("association") == "significant").alias("is_significant")
).drop("association").lazy()
variants.head(5).collect(engine="streaming")

shape: (5, 9)
┌──────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────┬───────────────────────┬───────────┬─────────────┬─────────────────┬────────────────┐
│ rsid     ┆ study_design                                                                                                                                        ┆ conclusions                                                                                                                                                           ┆ gender      ┆ quickref              ┆ quickyear ┆ quickpubmed ┆ population_name ┆ is_significant │
│ ---      ┆ ---                                                                                                                                                 ┆ ---                                                                                                                                                                   ┆ ---         ┆ ---                   ┆ ---       ┆ ---         ┆ ---             ┆ ---            │
│ str      ┆ str                                                                                                                                                 ┆ str                                                                                                                                                                   ┆ str         ┆ str                   ┆ i64       ┆ str         ┆ str             ┆ bool           │
╞══════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═════════════╪═══════════════════════╪═══════════╪═════════════╪═════════════════╪════════════════╡
│ HLA-DRB5 ┆ 964 inhabitants aged 85 years and over and 2444 young controls, aged 20-35 years, with an identical ethnic and demographic background were examined ┆ Without correcting for multiple testing, HLA-DR5 was higher in the group of 85 years and over, as compared to the control group                                       ┆ male/female ┆ Lagaay et al. (1991)  ┆ 1991      ┆ 1859103     ┆ Dutch           ┆ false          │
│ APOB     ┆ The apolipoprotein B Xba I polymorphism was examined in 179 Finnish centenarians                                                                    ┆ The frequencies of the Xba I alleles among the centenarians and among the young Finns were not significantly different                                                ┆ male/female ┆ Louhija et al. (1994) ┆ 1994      ┆ 8018664     ┆ Finnish         ┆ false          │
│ HLA-B40  ┆ 964 inhabitants aged 85 years and over and 2444 young controls, aged 20-35 years, with an identical ethnic and demographic background were examined ┆ Without correcting for multiple testing, HLA-B40 was lower in the group of 85 years and over, as compared to the control group                                        ┆ male/female ┆ Lagaay et al. (1991)  ┆ 1991      ┆ 1859103     ┆ Dutch           ┆ false          │
│ APOC3    ┆ The Sst I polymorphism was examined in 179 Finnish centenarians                                                                                     ┆ The S2 allele (Sst I restriction site present) occurred more often in the centenarians (frequency, 12.9%) than in the youngest reference population (frequency, 8.8%) ┆ male/female ┆ Louhija et al. (1994) ┆ 1994      ┆ 8018664     ┆ Finnish         ┆ true           │
│ rs7412   ┆ The common polymorphism of apolipoprotein E (E2, E3, and E4) was examined in 179 Finnish centenarians                                               ┆ The frequency of the E2 allele was higher and that of the E4 allele lower in the centenarians                                                                         ┆ male/female ┆ Louhija et al. (1994) ┆ 1994      ┆ 8018664     ┆ Finnish         ┆ true           │
└──────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────┴───────────────────────┴───────────┴─────────────┴─────────────────┴────────────────┘

In [16]:
extended_weights = weights.join(variants, on="rsid")#.filter(pl.col("is_significant"))
extended_weights.head(5).collect(engine="streaming")

shape: (5, 15)
┌───────────┬────────┬───────┬──────────┬────────┬──────────┬──────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────┬───────────────────────┬───────────┬─────────────┬────────────────────┬────────────────┐
│ rsid      ┆ allele ┆ state ┆ zygosity ┆ weight ┆ priority ┆ name         ┆ study_design                                                                                                                                                                                                                                                    ┆ conclusions                                                                                                                                                         ┆ gender      ┆ quickref              ┆ quickyear ┆ quickpubmed ┆ population_name    ┆ is_significant │
│ ---       ┆ ---    ┆ ---   ┆ ---      ┆ ---    ┆ ---      ┆ ---          ┆ ---                                                                                                                                                                                                                                                             ┆ ---                                                                                                                                                                 ┆ ---         ┆ ---                   ┆ ---       ┆ ---         ┆ ---                ┆ ---            │
│ str       ┆ str    ┆ str   ┆ str      ┆ f64    ┆ str      ┆ str          ┆ str                                                                                                                                                                                                                                                             ┆ str                                                                                                                                                                 ┆ str         ┆ str                   ┆ i64       ┆ str         ┆ str                ┆ bool           │
╞═══════════╪════════╪═══════╪══════════╪════════╪══════════╪══════════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═════════════╪═══════════════════════╪═══════════╪═════════════╪════════════════════╪════════════════╡
│ rs1800896 ┆ C      ┆ alt   ┆ het      ┆ 0.25   ┆ 0.5      ┆ inflammation ┆ 112 (36 male, 76 female) centenarians, as well as 137 sixty-year-old controls, were analyzed for -1082G/A SNP                                                                                                                                                   ┆ No significant differences were observed in centenarians and controls                                                                                               ┆ male/female ┆ Pes et al. (2004)     ┆ 2004      ┆ 15462469    ┆ Italian (Sardinia) ┆ false          │
│ rs1800896 ┆ C      ┆ alt   ┆ hom      ┆ 0.5    ┆ 0.5      ┆ inflammation ┆ 112 (36 male, 76 female) centenarians, as well as 137 sixty-year-old controls, were analyzed for -1082G/A SNP                                                                                                                                                   ┆ No significant differences were observed in centenarians and controls                                                                                               ┆ male/female ┆ Pes et al. (2004)     ┆ 2004      ┆ 15462469    ┆ Italian (Sardinia) ┆ false          │
│ rs1800795 ┆ C      ┆ ref   ┆ hom      ┆ 0.6    ┆ 0.6      ┆ inflammation ┆ 100 control samples (59% female and 41% male) and 93 aged consecutive samples (70% female, 30% male with an age range of 80-97 years) were analyzed for -174G/C SNP                                                                                             ┆ No significant difference between centenarians and controls was observed                                                                                            ┆ male/female ┆ Ross et al. (2003)    ┆ 2003      ┆ 12714268    ┆ Irish              ┆ false          │
│ rs1800795 ┆ G      ┆ alt   ┆ het      ┆ 0.3    ┆ 0.6      ┆ inflammation ┆ 100 control samples (59% female and 41% male) and 93 aged consecutive samples (70% female, 30% male with an age range of 80-97 years) were analyzed for -174G/C SNP                                                                                             ┆ No significant difference between centenarians and controls was observed                                                                                            ┆ male/female ┆ Ross et al. (2003)    ┆ 2003      ┆ 12714268    ┆ Irish              ┆ false          │
│ rs1800795 ┆ C      ┆ ref   ┆ hom      ┆ 0.6    ┆ 0.6      ┆ inflammation ┆ -174G/C SNP was examined in 17 unrelated elderly (age 65-90 years; 6 males and 11 females), 23 family members (age 18-57 years; 9 males and 14 females, and a control group with 105 randomly selected, matched for geographical distribution healthy controls  ┆ GC genotype was higher in elders while GG genotype was lower in elders, though differences were not statistically significant after correcting for multiple testing ┆ male/female ┆ Naumova et al. (2004) ┆ 2004      ┆ 15050300    ┆ Bulgarian          ┆ false          │
└───────────┴────────┴───────┴──────────┴────────┴──────────┴──────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────┴───────────────────────┴───────────┴─────────────┴────────────────────┴────────────────┘

In [17]:
genome = pl.scan_parquet(str(ensembl_cache) + "/*.parquet", low_memory=True)
genome.head(5).collect(engine="streaming")

shape: (5, 41)
┌───────┬───────┬───────┬──────────────┬─────┬───────┬─────────────────┬──────┬────────┬────────────┬────────────────┬───────────┬───────────────────┬─────┬─────────┬─────────────────────────┬────────┬──────────┬──────────┬────────────────────────┬───────┬──────────┬─────────┬────────┬──────────────────┬─────────────────┬──────────────────────────┬────────────┬────────────────────┬─────────────────────────────┬─────────────┬────────────────────────┬─────────────────┬────────────────────┬─────────────────────────┬───────────────────┬──────────────────┬──────┬──────┬──────┬──────┐
│ chrom ┆ start ┆ end   ┆ id           ┆ ref ┆ alt   ┆ alts            ┆ qual ┆ filter ┆ COSMIC_101 ┆ ClinVar_202502 ┆ dbSNP_156 ┆ HGMD-PUBLIC_20204 ┆ TSA ┆ E_Cited ┆ E_Multiple_observations ┆ E_Freq ┆ E_TOPMed ┆ E_Hapmap ┆ E_Phenotype_or_Disease ┆ E_ESP ┆ E_gnomAD ┆ E_1000G ┆ E_ExAC ┆ CLIN_risk_factor ┆ CLIN_protective ┆ CLIN_confers_sensitivity ┆ CLIN_other ┆ CLIN_drug_response ┆ CLIN_uncertain_significance ┆ CLIN_benign ┆ CLIN_likely_pathogenic ┆ CLIN_pathogenic ┆ CLIN_likely_benign ┆ CLIN_histocompatibility ┆ CLIN_not_provided ┆ CLIN_association ┆ MA   ┆ MAF  ┆ MAC  ┆ AA   │
│ ---   ┆ ---   ┆ ---   ┆ ---          ┆ --- ┆ ---   ┆ ---             ┆ ---  ┆ ---    ┆ ---        ┆ ---            ┆ ---       ┆ ---               ┆ --- ┆ ---     ┆ ---                     ┆ ---    ┆ ---      ┆ ---      ┆ ---                    ┆ ---   ┆ ---      ┆ ---     ┆ ---    ┆ ---              ┆ ---             ┆ ---                      ┆ ---        ┆ ---                ┆ ---                         ┆ ---         ┆ ---                    ┆ ---             ┆ ---                ┆ ---                     ┆ ---               ┆ ---              ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str   ┆ u32   ┆ u32   ┆ str          ┆ str ┆ str   ┆ list[str]       ┆ f64  ┆ str    ┆ bool       ┆ bool           ┆ bool      ┆ bool              ┆ str ┆ bool    ┆ bool                    ┆ bool   ┆ bool     ┆ bool     ┆ bool                   ┆ bool  ┆ bool     ┆ bool    ┆ bool   ┆ bool             ┆ bool            ┆ bool                     ┆ bool       ┆ bool               ┆ bool                        ┆ bool        ┆ bool                   ┆ bool            ┆ bool               ┆ bool                    ┆ bool              ┆ bool             ┆ str  ┆ f32  ┆ i32  ┆ str  │
╞═══════╪═══════╪═══════╪══════════════╪═════╪═══════╪═════════════════╪══════╪════════╪════════════╪════════════════╪═══════════╪═══════════════════╪═════╪═════════╪═════════════════════════╪════════╪══════════╪══════════╪════════════════════════╪═══════╪══════════╪═════════╪════════╪══════════════════╪═════════════════╪══════════════════════════╪════════════╪════════════════════╪═════════════════════════════╪═════════════╪════════════════════════╪═════════════════╪════════════════════╪═════════════════════════╪═══════════════════╪══════════════════╪══════╪══════╪══════╪══════╡
│ 1     ┆ 10001 ┆ 10001 ┆ rs1570391677 ┆ T   ┆ A|C   ┆ ["A", "C"]      ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10002 ┆ 10002 ┆ rs1570391692 ┆ A   ┆ C     ┆ ["C"]           ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10003 ┆ 10003 ┆ rs1570391694 ┆ A   ┆ C     ┆ ["C"]           ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10007 ┆ 10007 ┆ rs1639538116 ┆ T   ┆ C|G   ┆ ["C", "G"]      ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10008 ┆ 10008 ┆ rs1570391698 ┆ A   ┆ C|G|T ┆ ["C", "G", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
└───────┴───────┴───────┴──────────────┴─────┴───────┴─────────────────┴──────┴────────┴────────────┴────────────────┴───────────┴───────────────────┴─────┴─────────┴─────────────────────────┴────────┴──────────┴──────────┴────────────────────────┴───────┴──────────┴─────────┴────────┴──────────────────┴─────────────────┴──────────────────────────┴────────────┴────────────────────┴─────────────────────────────┴─────────────┴────────────────────────┴─────────────────┴────────────────────┴─────────────────────────┴───────────────────┴──────────────────┴──────┴──────┴──────┴──────┘

In [61]:
genome.columns

/tmp/ipykernel_16798/3095084027.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  genome.columns

['chrom',
 'start',
 'end',
 'id',
 'ref',
 'alt',
 'alts',
 'qual',
 'filter',
 'COSMIC_101',
 'ClinVar_202502',
 'dbSNP_156',
 'HGMD-PUBLIC_20204',
 'TSA',
 'E_Cited',
 'E_Multiple_observations',
 'E_Freq',
 'E_TOPMed',
 'E_Hapmap',
 'E_Phenotype_or_Disease',
 'E_ESP',
 'E_gnomAD',
 'E_1000G',
 'E_ExAC',
 'CLIN_risk_factor',
 'CLIN_protective',
 'CLIN_confers_sensitivity',
 'CLIN_other',
 'CLIN_drug_response',
 'CLIN_uncertain_significance',
 'CLIN_benign',
 'CLIN_likely_pathogenic',
 'CLIN_pathogenic',
 'CLIN_likely_benign',
 'CLIN_histocompatibility',
 'CLIN_not_provided',
 'CLIN_association',
 'MA',
 'MAF',
 'MAC',
 'AA']

In [18]:
longevitymap_annotations = (
    genome.rename({"id": "rsid"})
    .join(extended_weights, on="rsid")
    .filter(pl.col("alts").list.contains(pl.col("allele")))
)
longevitymap_annotations.head(5).collect(engine="streaming")

shape: (5, 55)
┌───────┬──────────┬──────────┬────────────┬─────┬─────┬────────────┬──────┬────────┬────────────┬────────────────┬───────────┬───────────────────┬─────┬─────────┬─────────────────────────┬────────┬──────────┬──────────┬────────────────────────┬───────┬──────────┬─────────┬────────┬──────────────────┬─────────────────┬──────────────────────────┬────────────┬────────────────────┬─────────────────────────────┬─────────────┬────────────────────────┬─────────────────┬────────────────────┬─────────────────────────┬───────────────────┬──────────────────┬─────┬──────────┬──────┬─────┬────────┬───────┬──────────┬────────┬──────────┬──────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────┬─────────────┬──────────────────────────┬───────────┬─────────────┬──────────────────────┬────────────────┐
│ chrom ┆ start    ┆ end      ┆ rsid       ┆ ref ┆ alt ┆ alts       ┆ qual ┆ filter ┆ COSMIC_101 ┆ ClinVar_202502 ┆ dbSNP_156 ┆ HGMD-PUBLIC_20204 ┆ TSA ┆ E_Cited ┆ E_Multiple_observations ┆ E_Freq ┆ E_TOPMed ┆ E_Hapmap ┆ E_Phenotype_or_Disease ┆ E_ESP ┆ E_gnomAD ┆ E_1000G ┆ E_ExAC ┆ CLIN_risk_factor ┆ CLIN_protective ┆ CLIN_confers_sensitivity ┆ CLIN_other ┆ CLIN_drug_response ┆ CLIN_uncertain_significance ┆ CLIN_benign ┆ CLIN_likely_pathogenic ┆ CLIN_pathogenic ┆ CLIN_likely_benign ┆ CLIN_histocompatibility ┆ CLIN_not_provided ┆ CLIN_association ┆ MA  ┆ MAF      ┆ MAC  ┆ AA  ┆ allele ┆ state ┆ zygosity ┆ weight ┆ priority ┆ name             ┆ study_design                                                                                                                                        ┆ conclusions                                                                               ┆ gender      ┆ quickref                 ┆ quickyear ┆ quickpubmed ┆ population_name      ┆ is_significant │
│ ---   ┆ ---      ┆ ---      ┆ ---        ┆ --- ┆ --- ┆ ---        ┆ ---  ┆ ---    ┆ ---        ┆ ---            ┆ ---       ┆ ---               ┆ --- ┆ ---     ┆ ---                     ┆ ---    ┆ ---      ┆ ---      ┆ ---                    ┆ ---   ┆ ---      ┆ ---     ┆ ---    ┆ ---              ┆ ---             ┆ ---                      ┆ ---        ┆ ---                ┆ ---                         ┆ ---         ┆ ---                    ┆ ---             ┆ ---                ┆ ---                     ┆ ---               ┆ ---              ┆ --- ┆ ---      ┆ ---  ┆ --- ┆ ---    ┆ ---   ┆ ---      ┆ ---    ┆ ---      ┆ ---              ┆ ---                                                                                                                                                 ┆ ---                                                                                       ┆ ---         ┆ ---                      ┆ ---       ┆ ---         ┆ ---                  ┆ ---            │
│ str   ┆ u32      ┆ u32      ┆ str        ┆ str ┆ str ┆ list[str]  ┆ f64  ┆ str    ┆ bool       ┆ bool           ┆ bool      ┆ bool              ┆ str ┆ bool    ┆ bool                    ┆ bool   ┆ bool     ┆ bool     ┆ bool                   ┆ bool  ┆ bool     ┆ bool    ┆ bool   ┆ bool             ┆ bool            ┆ bool                     ┆ bool       ┆ bool               ┆ bool                        ┆ bool        ┆ bool                   ┆ bool            ┆ bool               ┆ bool                    ┆ bool              ┆ bool             ┆ str ┆ f32      ┆ i32  ┆ str ┆ str    ┆ str   ┆ str      ┆ f64    ┆ str      ┆ str              ┆ str                                                                                                                                                 ┆ str                                                                                       ┆ str         ┆ str                      ┆ i64       ┆ str         ┆ str                  ┆ bool           │
╞═══════╪══════════╪══════════╪════════════╪═════╪═════╪════════════╪══════╪════════╪════════════╪════════════════╪═══════════╪═══════════════════╪═════╪═════════╪═════════════════════════╪════════╪══════════╪══════════╪════════════════════════╪═══════╪══════════╪═════════╪════════╪══════════════════╪═════════════════╪══════════════════════════╪════════════╪════════════════════╪═════════════════════════════╪═════════════╪════════════════════════╪═════════════════╪════════════════════╪═════════════════════════╪═══════════════════╪══════════════════╪═════╪══════════╪══════╪═════╪════════╪═══════╪══════════╪════════╪══════════╪══════════════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════════════════════════════════════════╪═════════════╪══════════════════════════╪═══════════╪═════════════╪══════════════════════╪════════════════╡
│ 1     ┆ 11340352 ┆ 11340352 ┆ rs3120819  ┆ A   ┆ C|T ┆ ["C", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ true    ┆ false                   ┆ true   ┆ true     ┆ false    ┆ false                  ┆ false ┆ true     ┆ true    ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ C   ┆ 0.452119 ┆ 2304 ┆ A   ┆ C      ┆ alt   ┆ het      ┆ 0.24   ┆ 0.48     ┆ tumor-suppressor ┆ Genome-wide association study using 1,471 genotyped participants from the Framingham Heart Study, of which 1,173 individuals had known lifespans,   ┆ A total of 27 SNPs were identified at the intersection of various statistical procedures. ┆ male/female ┆ Yashin et al. (2012)     ┆ 2012      ┆ 22533364    ┆ American (Caucasian) ┆ true           │
│       ┆          ┆          ┆            ┆     ┆     ┆            ┆      ┆        ┆            ┆                ┆           ┆                   ┆     ┆         ┆                         ┆        ┆          ┆          ┆                        ┆       ┆          ┆         ┆        ┆                  ┆                 ┆                          ┆            ┆                    ┆                             ┆             ┆                        ┆                 ┆                    ┆                         ┆                   ┆                  ┆     ┆          ┆      ┆     ┆        ┆       ┆          ┆        ┆          ┆                  ┆ plus 517 individuals from the Offspring cohort for validating connections between longevity and genetic variants                                    ┆                                                                                           ┆             ┆                          ┆           ┆             ┆                      ┆                │
│ 1     ┆ 11340352 ┆ 11340352 ┆ rs3120819  ┆ A   ┆ C|T ┆ ["C", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ true    ┆ false                   ┆ true   ┆ true     ┆ false    ┆ false                  ┆ false ┆ true     ┆ true    ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ C   ┆ 0.452119 ┆ 2304 ┆ A   ┆ C      ┆ alt   ┆ hom      ┆ 0.48   ┆ 0.48     ┆ tumor-suppressor ┆ Genome-wide association study using 1,471 genotyped participants from the Framingham Heart Study, of which 1,173 individuals had known lifespans,   ┆ A total of 27 SNPs were identified at the intersection of various statistical procedures. ┆ male/female ┆ Yashin et al. (2012)     ┆ 2012      ┆ 22533364    ┆ American (Caucasian) ┆ true           │
│       ┆          ┆          ┆            ┆     ┆     ┆            ┆      ┆        ┆            ┆                ┆           ┆                   ┆     ┆         ┆                         ┆        ┆          ┆          ┆                        ┆       ┆          ┆         ┆        ┆                  ┆                 ┆                          ┆            ┆                    ┆                             ┆             ┆                        ┆                 ┆                    ┆                         ┆                   ┆                  ┆     ┆          ┆      ┆     ┆        ┆       ┆          ┆        ┆          ┆                  ┆ plus 517 individuals from the Offspring cohort for validating connections between longevity and genetic variants                                    ┆                                                                                           ┆             ┆                          ┆           ┆             ┆                      ┆                │
│ 1     ┆ 12513771 ┆ 12513771 ┆ rs12129750 ┆ A   ┆ C|G ┆ ["C", "G"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ true     ┆ false    ┆ false                  ┆ false ┆ true     ┆ true    ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ A   ┆ 0.152669 ┆ 778  ┆ G   ┆ G      ┆ alt   ┆ het      ┆ 0.07   ┆ 0.14     ┆ other            ┆ Genome-wide association study in 801 centenarians and 914 healthy controls                                                                          ┆ 281 SNPs were found to discriminate between cases and controls                            ┆ male/female ┆ Sebastiani et al. (2012) ┆ 2012      ┆ 22279548    ┆ American (Caucasian) ┆ true           │
│ 1     ┆ 12513771 ┆ 12513771 ┆ rs12129750 ┆ A   ┆ C|G ┆ ["C", "G"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ true     ┆ false    ┆ false                  ┆ false ┆ true     ┆ true    ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ A   ┆ 0.152669 ┆ 778  ┆ G   ┆ G      ┆ alt   ┆ hom      ┆ 0.14   ┆ 0.14     ┆ other            ┆ Genome-wide association study in 801 centenarians and 914 healthy controls                                                                          ┆ 281 SNPs were found to discriminate between cases and controls                            ┆ male/female ┆ Sebastiani et al. (2012) ┆ 2012      ┆ 22279548    ┆ American (Caucasian) ┆ true           │
│ 1     ┆ 21355143 ┆ 21355143 ┆ rs2745252  ┆ T   ┆ C   ┆ ["C"]      ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ true     ┆ false    ┆ false                  ┆ false ┆ true     ┆ true    ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ C   ┆ 0.172881 ┆ 881  ┆ T   ┆ C      ┆ alt   ┆ hom      ┆ 0.14   ┆ 0.14     ┆ other            ┆ Genome-wide association study in 801 centenarians and 914 healthy controls                                                                          ┆ 281 SNPs were found to discriminate between cases and controls                            ┆ male/female ┆ Sebastiani et al. (2012) ┆ 2012      ┆ 22279548    ┆ American (Caucasian) ┆ true           │
└───────┴──────────┴──────────┴────────────┴─────┴─────┴────────────┴──────┴────────┴────────────┴────────────────┴───────────┴───────────────────┴─────┴─────────┴─────────────────────────┴────────┴──────────┴──────────┴────────────────────────┴───────┴──────────┴─────────┴────────┴──────────────────┴─────────────────┴──────────────────────────┴────────────┴────────────────────┴─────────────────────────────┴─────────────┴────────────────────────┴─────────────────┴────────────────────┴─────────────────────────┴───────────────────┴──────────────────┴─────┴──────────┴──────┴─────┴────────┴───────┴──────────┴────────┴──────────┴──────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────┴─────────────┴──────────────────────────┴───────────┴─────────────┴──────────────────────┴────────────────┘

In [19]:
modules_output = data / "output" / "modules"
modules_output.mkdir(parents=True, exist_ok=True)
where = modules_output / "longevitymap_annotations.parquet"
longevitymap_annotations.sink_parquet(where, engine="streaming")

## Prepare other modules

In [20]:
tprint(modules)

modules
	.gitignore
	just_drugs
		annotation_tab.tsv
	just_longevitymap
		longevitymap.sqlite
	just_coronary
		coronary.sqlite
	just_lipidmetabolism
		lipid_metabolism.sqlite
	just_vo2max
		vo2max.sqlite
	longevitymap_annotations.parquet
	just_superhuman
		superhuman.sqlite
	just_prs
		prs.sqlite
	just_cancer
		genes.txt

In [27]:
coronary_db = modules / "just_coronary" / "coronary.sqlite"
conn_coronary = sqlite3.connect(coronary_db)
coronary = pl.read_database("SELECT * FROM coronary_disease", connection=conn_coronary).lazy()
coronary.head(5).collect(engine="streaming")

shape: (5, 15)
┌─────┬────────────┬────────────┬────────────┬────────────┬─────────────┬──────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────┬─────────────────────────────────────────────────────────────────────────────┬─────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────┬──────────┬───────┐
│ id  ┆ rsID       ┆ Gene       ┆ Ref_allele ┆ Alt_allele ┆ Risk_allele ┆ Genotype ┆ Conclusion                                                                                                                                                                                                                                                                                                                                                                            ┆ Weight ┆ PMID                                                                        ┆ Population      ┆ GWAS_study_design                                                                                                                                                                                                                                                                                                                                                    ┆ P_value                                                ┆ zygosity ┆ state │
│ --- ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---         ┆ ---      ┆ ---                                                                                                                                                                                                                                                                                                                                                                                   ┆ ---    ┆ ---                                                                         ┆ ---             ┆ ---                                                                                                                                                                                                                                                                                                                                                                  ┆ ---                                                    ┆ ---      ┆ ---   │
│ i64 ┆ str        ┆ str        ┆ str        ┆ str        ┆ str         ┆ str      ┆ str                                                                                                                                                                                                                                                                                                                                                                                   ┆ str    ┆ str                                                                         ┆ str             ┆ str                                                                                                                                                                                                                                                                                                                                                                  ┆ str                                                    ┆ str      ┆ str   │
╞═════╪════════════╪════════════╪════════════╪════════════╪═════════════╪══════════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪════════╪═════════════════════════════════════════════════════════════════════════════╪═════════════════╪══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪════════════════════════════════════════════════════════╪══════════╪═══════╡
│ 1   ┆ rs4977574  ┆ CDKN2B-AS1 ┆ A          ┆ G          ┆ G           ┆ AA       ┆ Several GWASs have revealed that the single nucleotide polymorphism (SNP) rs4977574 of ANRIL (CDKN2B-AS1) was associated with increased CAD risk in different ethnicities. Gene product may affect development of CAD via regulating vascular cell proliferation with reduced expression of CDKN2A and CDKN2B. GG-carriers has 1.54 times increased susceptibility to Coronary artery ┆ -1.54  ┆ PMID 17478681; PMID 21378990; PMID 21378988; PMID 24916648; PMID: 30278588; ┆ European; Asian ┆ [PMID 29263402]: Discovery sample description: 1,778 Chinese ancestry cases, 391 Malay ancestry cases, 5,164 Chinese ancestry controls, 2,212 Malay ancestry controls Discovery ancestry (country of recruitment): 2603 South East Asian (Singapore), 6942 East Asian (Singapore); [PMID 29263402]: Discovery sample description: 1,808 European ancestry cases, 915 ┆ [PMID 29263402]: 1 x 10-7; [PMID 21239051]: 1 x 10-14; ┆ hom      ┆ alt   │
│     ┆            ┆            ┆            ┆            ┆             ┆          ┆ disease (for Europeans) [PMID 17478681]. In meta-analysis it was shown, that rs4977574 in ANRIL increased CAD risk in Asian population [PMID: 30278588].                                                                                                                                                                                                                              ┆        ┆                                                                             ┆                 ┆ European ancestry controls Discovery ancestry (country of recruitment): 2723 European (U.S.); Replication sample description: 10,585 European ancestry cases, 6,468 European ancestry controls;  Replication ancestry (country of recruitment): 17053 European (U.S.)                                                                                                ┆                                                        ┆          ┆       │
│ 2   ┆ rs4977574  ┆ CDKN2B-AS1 ┆ A          ┆ G          ┆ G           ┆ AG       ┆ Several GWASs have revealed that the single nucleotide polymorphism (SNP) rs4977574 of ANRIL (CDKN2B-AS1) was associated with increased CAD risk in different ethnicities. Gene product may affect development of CAD via regulating vascular cell proliferation with reduced expression of CDKN2A and CDKN2B. GA-carriers has 1.3 times increased susceptibility to Coronary artery  ┆ -1.3   ┆ PMID 17478681; PMID 21378990; PMID 21378988; PMID 24916648; PMID: 30278588  ┆ European; Asian ┆ [PMID 29263402]: Discovery sample description: 1,778 Chinese ancestry cases, 391 Malay ancestry cases, 5,164 Chinese ancestry controls, 2,212 Malay ancestry controls Discovery ancestry (country of recruitment): 2603 South East Asian (Singapore), 6942 East Asian (Singapore); [PMID 29263402]: Discovery sample description: 1,808 European ancestry cases, 915 ┆ [PMID 29263402]: 1 x 10-7; [PMID 21239051]: 1 x 10-14; ┆ hom      ┆ ref   │
│     ┆            ┆            ┆            ┆            ┆             ┆          ┆ disease (for Europeans) [PMID 17478681]. In meta-analysis it was shown, that rs4977574 in ANRIL increased CAD risk in Asian population [PMID: 30278588].                                                                                                                                                                                                                              ┆        ┆                                                                             ┆                 ┆ European ancestry controls Discovery ancestry (country of recruitment): 2723 European (U.S.); Replication sample description: 10,585 European ancestry cases, 6,468 European ancestry controls;  Replication ancestry (country of recruitment): 17053 European (U.S.)                                                                                                ┆                                                        ┆          ┆       │
│ 3   ┆ rs4977574  ┆ CDKN2B-AS1 ┆ A          ┆ G          ┆ G           ┆ GG       ┆ Several GWASs have revealed that the single nucleotide polymorphism (SNP) rs4977574 of ANRIL (CDKN2B-AS1) was associated with increased CAD risk in different ethnicities. Gene product may affect development of CAD via regulating vascular cell proliferation with reduced expression of CDKN2A and CDKN2B. Your genotype GG does not contain the risk indicating typical risk for ┆ 0      ┆ PMID 17478681; PMID 21378990; PMID 21378988; PMID 24916648; PMID: 30278588; ┆ European; Asian ┆ [PMID 29263402]: Discovery sample description: 1,778 Chinese ancestry cases, 391 Malay ancestry cases, 5,164 Chinese ancestry controls, 2,212 Malay ancestry controls Discovery ancestry (country of recruitment): 2603 South East Asian (Singapore), 6942 East Asian (Singapore); [PMID 29263402]: Discovery sample description: 1,808 European ancestry cases, 915 ┆ [PMID 29263402]: 1 x 10-7; [PMID 21239051]: 1 x 10-14; ┆ het      ┆ alt   │
│     ┆            ┆            ┆            ┆            ┆             ┆          ┆ Coronary artery disease.                                                                                                                                                                                                                                                                                                                                                              ┆        ┆                                                                             ┆                 ┆ European ancestry controls Discovery ancestry (country of recruitment): 2723 European (U.S.); Replication sample description: 10,585 European ancestry cases, 6,468 European ancestry controls;  Replication ancestry (country of recruitment): 17053 European (U.S.)                                                                                                ┆                                                        ┆          ┆       │
│ 4   ┆ rs17672135 ┆ FMN2       ┆ T          ┆ C          ┆ C           ┆ TT       ┆ FMN2 gene product  plays a role in responses to DNA damage, cellular stress and hypoxia (PubMed:23375502). rs17672135 has been reported to be associated with heart disease, in particular, coronary artery disease [PMID 17554300]. TT carriers was reported to have 1.3x increased risk of heart disease.                                                                           ┆ -0.3   ┆ PMID 19956433; PMID 17554300; PMID 20017983;                                ┆ European        ┆ [PMID 17554300]: Discovery sample description: 1,926 European ancestry cases, 2,938 European ancestry controls:  Discovery ancestry (country of recruitment): 4864 European (U.K.)                                                                                                                                                                                   ┆ [PMID 17554300]: 2 x 10-6                              ┆ hom      ┆ ref   │
│ 5   ┆ rs17672135 ┆ FMN2       ┆ T          ┆ C          ┆ C           ┆ TC       ┆ FMN2 gene product  plays a role in responses to DNA damage, cellular stress and hypoxia (PubMed:23375502). rs17672135 has been reported to be associated with heart disease, in particular, coronary artery disease [PMID 17554300]. TC carriers was NOT reported to have  increased risk of heart disease.                                                                           ┆ 0      ┆ PMID 19956433; PMID 17554300; PMID 20017983;                                ┆ European        ┆ [PMID 17554300]: Discovery sample description: 1,926 European ancestry cases, 2,938 European ancestry controls:  Discovery ancestry (country of recruitment): 4864 European (U.K.)                                                                                                                                                                                   ┆ [PMID 17554300]: 2 x 10-6                              ┆ het      ┆ alt   │
└─────┴────────────┴────────────┴────────────┴────────────┴─────────────┴──────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────┴─────────────────────────────────────────────────────────────────────────────┴─────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────┴──────────┴───────┘

# Lipidmetabolism

In [ ]:
lipid_metabolism_db = modules / "just_lipidmetabolism" / "lipid_metabolism.sqlite"
conn_lipid = sqlite3.connect(lipid_metabolism_db)
print(f"Tables in Lipid Metabolism: {list_tables(conn_lipid)}")

Tables in Lipid Metabolism: [('rsids',), ('studies',), ('weight',)]

In [33]:
print_tables(conn_lipid)

Schema for table 'rsids':
  index (INTEGER)
  rsid (TEXT)
  gene (TEXT)
  ref_allele (TEXT)
  alt_allele (TEXT)
  risk_allele (TEXT)
  rsid_conclusion (TEXT)
  pmids (TEXT)
  population (TEXT)
  p_value (TEXT)

Schema for table 'studies':
  index (INTEGER)
  pubmed_id (INTEGER)
  snp (TEXT)
  populations (TEXT)
  p_value (TEXT)

Schema for table 'weight':
  index (INTEGER)
  rsid (TEXT)
  genotype (TEXT)
  weight (TEXT)
  genotype_specific_conclusion (TEXT)
  ref_allele (TEXT)
  alt_allele (TEXT)
  risk_allele (TEXT)
  allele (TEXT)
  state (TEXT)
  zygosity (TEXT)

[('rsids',), ('studies',), ('weight',)]

In [35]:
lipid_rsids = pl.read_database("SELECT * FROM rsids", connection=conn_lipid).lazy()
lipid_rsids.head(5).collect(engine="streaming")
# VOMax

shape: (5, 10)
┌───────┬──────────┬──────┬────────────┬────────────┬─────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────┬───────────┐
│ index ┆ rsid     ┆ gene ┆ ref_allele ┆ alt_allele ┆ risk_allele ┆ rsid_conclusion                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ┆ pmids                                                                                   ┆ population                                     ┆ p_value   │
│ ---   ┆ ---      ┆ ---  ┆ ---        ┆ ---        ┆ ---         ┆ ---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ┆ ---                                                                                     ┆ ---                                            ┆ ---       │
│ i64   ┆ str      ┆ str  ┆ str        ┆ str        ┆ str         ┆ str                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ┆ str                                                                                     ┆ str                                            ┆ str       │
╞═══════╪══════════╪══════╪════════════╪════════════╪═════════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════════╪════════════════════════════════════════════════╪═══════════╡
│ 0     ┆ rs328    ┆ LPL  ┆ C          ┆ G          ┆ G           ┆ The LPL gene provides instructions for making the enzyme lipoprotein lipase, which breaks down fats in the body. To be precise it is responsible for the hydrolysis of triglycerides and very low-density lipoproteins (VLDL).  A particular variant of the LPL gene, called rs328, has been studied for its potential associations with various health conditions. This SNP is also called LPL 1595C>G or LPL Ser447X. The S447X mutation is a variant in the LPL (lipoprotein lipase) gene that results in a deficiency of functional LPL enzyme. This mutation has been associated with impaired lipid metabolism and an increased risk of certain metabolic disorders. Individuals with the S447X mutation may have high levels of triglycerides in their blood, which can increase the risk of         ┆ [PMID: 18193044]; [PMID: 30944368]; [PMID: 19148283];                                   ┆ European; African                              ┆ 2,00E-28  │
│       ┆          ┆      ┆            ┆            ┆             ┆ pancreatitis and other health problems. This mutation may also increase the risk of developing coronary artery disease, a condition in which the arteries that supply blood to the heart become narrowed or blocked. The S447X mutat…                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ┆                                                                                         ┆                                                ┆           │
│ 1     ┆ rs268    ┆ LPL  ┆ A          ┆ G          ┆ G           ┆ LPL is an enzyme that plays a key role in the breakdown and utilization of fats in the body. rs268, also known as LPL Asn291Ser as well as LPL N291S or N318S, a SNP in the lipoprotein lipase LPL gene, has been linked to increased susceptibility to hypertriglyceridemia, heart disease, Type-2 diabetes, idiopathic venous thromboembolism. This mutation has been shown to alter LPL activity and increase the risk of hypertriglyceridemia, a condition characterized by high levels of triglycerides in the blood. It's important to note that the impact of the N291S mutation on lipid metabolism and the risk of metabolic disorders can vary depending on other genetic and environmental factors.                                                                                              ┆ [PMID 22399527]; [PMID: 20429872]; [PMID 16741292]; [PMID 16651467];                    ┆ European;                                      ┆ 2,00E-12  │
│ 2     ┆ rs708272 ┆ CETP ┆ G          ┆ A          ┆ G           ┆ Cholesteryl ester transfer protein, encoded by CETP, plays a key role in the metabolism of high-density lipoproteins (HDL). rs708272, also known as the TaqIB polymorphism of the CETP gene, may influence the levels of the "good" cholesterols, the high density lipoprotein (HDL) cholesterols. It mediates the exchange of lipids between lipoproteins, resulting in the eventual uptake of cholesterol by hepatocytes (reverse cholesterol transport). High plasma CETP concentration is associated with reduced HDL concentrations and is a strong and independent risk factor for CAD.  Generally, the B2 allele (A-allele) is considered to lead to higher HDL levels, associated with reduced plasma CETP levels, and reduced risk of cardiovascular disease. Meta-analysis [PMID: 27608031] has   ┆ [PMID 18560005]; [PMID 20031564]; [PMID: 27608031]; [PMID: 31739638]; [PMID: 34503513]; ┆ European; Han Chinese; Asian; Western Siberia; ┆ 3,00E-11  │
│       ┆          ┆      ┆            ┆            ┆             ┆ shown that  CETP TaqIB polymorphism protects against composite ischemic CVD risk and is associated with a higher HDL-C concentration in both Asians and Caucasians.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ┆                                                                                         ┆                                                ┆           │
│ 3     ┆ rs429358 ┆ APOE ┆ T          ┆ C          ┆ C           ┆ Apolipoprotein E is encoded by the APOE gene, which plays a key role in lipid transport and metabolism and is essential in cholesterol homeostasis. Two SNPs lead to the formation of three APOE isoforms, E2, E3 and E4. Polymorphisms in APOE gene has been linked to cardiovascular disease (CVD), immunoregulation, cognitive decline and Alzheimer’s disease (AD), as well as infectious diseases. Carriers of the E4 allele tend to exhibit an increased risk for the above-mentioned chronic diseases. APOE E4 carriers may be more responsive to their external environment, where focusing on decreasing environmental stressors and pollution, ensuring quantity and quality of dietary fat is addressed, and increasing intake of phytonutrient rich foods, as well as including sufficient      ┆ [PMID 20429872]; [PMID 34887591];                                                       ┆ European; Asian; African;                      ┆ 6,00E-256 │
│       ┆          ┆      ┆            ┆            ┆             ┆ exercise, may prove beneficial in negating the effects of the SNP.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ┆                                                                                         ┆                                                ┆           │
│ 4     ┆ rs7412   ┆ APOE ┆ C          ┆ T          ┆ C           ┆ The APOE gene provides instructions for making a protein called apolipoprotein E. This protein plays a role in the metabolism of lipids (fats) in the body, specifically in the transport of cholesterol and other fats in the blood. There are three different versions (alleles) of the APOE gene: E2, E3, and E4. Each person inherits one copy of the APOE gene from each parent, so an individual can have two copies of the same allele (such as E2/E2 or E4/E4) or one copy of each (such as E3/E4). The specific combination of alleles that an individual has can influence their risk of developing certain health conditions. Research has suggested that E4 allele is  linked to cardiovascular disease (CVD), immunoregulation, cognitive decline and Alzheimer’s disease (AD), as well as     ┆ [PMID 20406466]; [PMID 20429872]; [PMID 22174202]; [PMID: 34887591]; [PMID: 28270201];  ┆ European; Asian; African;                      ┆ 6,00E-14  │
│       ┆          ┆      ┆            ┆            ┆             ┆ infectious diseases. Carriers of the E4 allele tend to exhibit an increased risk for the above-mentioned chronic diseases. Individuals with the E2 allele may have a lower risk of these conditions. APOE E4 carriers may be mor…                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ┆                                                                                         ┆                                                ┆           │
└───────┴──────────┴──────┴────────────┴────────────┴─────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────┴───────────┘

In [38]:
lipid_weights = pl.read_database("SELECT * FROM weight", connection=conn_lipid).lazy()
lipid_weights.head(5).collect(engine="streaming")

shape: (5, 11)
┌───────┬───────┬──────────┬────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────┬────────────┬─────────────┬────────┬───────┬──────────┐
│ index ┆ rsid  ┆ genotype ┆ weight ┆ genotype_specific_conclusion                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ┆ ref_allele ┆ alt_allele ┆ risk_allele ┆ allele ┆ state ┆ zygosity │
│ ---   ┆ ---   ┆ ---      ┆ ---    ┆ ---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ┆ ---        ┆ ---        ┆ ---         ┆ ---    ┆ ---   ┆ ---      │
│ i64   ┆ str   ┆ str      ┆ str    ┆ str                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ┆ str        ┆ str        ┆ str         ┆ str    ┆ str   ┆ str      │
╞═══════╪═══════╪══════════╪════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪════════════╪════════════╪═════════════╪════════╪═══════╪══════════╡
│ 0     ┆ rs328 ┆ CC       ┆ 0      ┆ You genotype is not associated with increased risk of lipid metabolism impairment.                                                                                                                                                                                                                                                                                                                                                                                                                                 ┆ C          ┆ G          ┆ G           ┆ C      ┆ ref   ┆ hom      │
│ 1     ┆ rs328 ┆ CG       ┆ -0.4   ┆ You are heterozygous carrier of the S447X (rs328) LPL polymorphism. That slightly incrase risk of  having high levels of triglycerides in blood. This mutation may also increase the risk of developing coronary artery disease, a condition in which the arteries that supply blood to the heart become narrowed or blocked. It have to mentioned, that risk of metabolic disorders can vary depending on other genetic and environmental factors.                                                                ┆ C          ┆ G          ┆ G           ┆ G      ┆ alt   ┆ het      │
│ 2     ┆ rs328 ┆ GG       ┆ -0.8   ┆ You have an unfavourable variant of S447X (rs328) LPL polymorphism. That incrase risk of  having high levels of triglycerides in blood. This mutation may also increase the risk of developing coronary artery disease, a condition in which the arteries that supply blood to the heart become narrowed or blocked. It have to mentioned, that risk of metabolic disorders can vary depending on other genetic and environmental factors.                                                                         ┆ C          ┆ G          ┆ G           ┆ G      ┆ alt   ┆ hom      │
│ 3     ┆ rs268 ┆ AA       ┆ 0      ┆ AA genotype is favourable and is not associated with impaired lipid metabolism.                                                                                                                                                                                                                                                                                                                                                                                                                                    ┆ A          ┆ G          ┆ G           ┆ A      ┆ ref   ┆ hom      │
│ 4     ┆ rs268 ┆ AG       ┆ -0.5   ┆ You are heterozygous carrier of the N291S (rs268) mutation, it means that you have one copy of the mutated gene and one copy of the normal gene. Carriers of the N291S mutation may not have any symptoms or health problems related to the mutation. However, it is important to be aware of the potential impact of the N291S mutation on lipid metabolism and the risk of metabolic disorders. Some research have shown heterozygous carriers have an increased risk of  venous thromboembolism [PMID 16651467] ┆ A          ┆ G          ┆ G           ┆ G      ┆ alt   ┆ het      │
└───────┴───────┴──────────┴────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────┴────────────┴─────────────┴────────┴───────┴──────────┘

In [40]:
studies = pl.read_database("SELECT * FROM studies", connection=conn_lipid).lazy()
studies.head(5).collect(engine="streaming")

shape: (5, 5)
┌───────┬───────────┬────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┐
│ index ┆ pubmed_id ┆ snp        ┆ populations                                                                                                                                                                                                                                                      ┆ p_value  │
│ ---   ┆ ---       ┆ ---        ┆ ---                                                                                                                                                                                                                                                              ┆ ---      │
│ i64   ┆ i64       ┆ str        ┆ str                                                                                                                                                                                                                                                              ┆ str      │
╞═══════╪═══════════╪════════════╪══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════╡
│ 0     ┆ 18193044  ┆ rs17145738 ┆ Discovery sample description: 2,758 European ancestry individuals Discovery ancestry (country of recruitment): 2758 European (NR)                                                                                                                                ┆ 7,00E-22 │
│ 1     ┆ 20686565  ┆ rs17145738 ┆ Discovery sample description: 96,598 European ancestry individuals
 Discovery ancestry (country of recruitment):   96598 European (Finland, Sweden, U.S., Australia, Iceland, Italy, Netherlands, Germany, U.K., Croatia, Switzerland, Austria, France, Denmark) ┆ 1,00E-09 │
│ 2     ┆ 18193044  ┆ rs328      ┆ Discovery sample description: 2,758 European ancestry individuals
 Discovery ancestry (country of recruitment): 2758 European (NR)                                                                                                                               ┆ 2,00E-28 │
│ 3     ┆ 22399527  ┆ rs268      ┆ Discovery sample description: 2,637 European ancestry cases, 7,927 European ancestry controls
 Discovery ancestry (country of recruitment): 10564 European (Finland)                                                                                             ┆ 2,00E-12 │
│ 4     ┆ 34503513  ┆ rs708272   ┆ Discovery sample description: 13,814 British ancestry individuals
 Discovery ancestry (country of recruitment): 13814 European (U.K.)                                                                                                                            ┆ 3,00E-11 │
└───────┴───────────┴────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────┘

# Superhuman

In [42]:
superhuman_db = modules / "just_superhuman" / "superhuman.sqlite"
conn_superhuman = sqlite3.connect(superhuman_db)
print_tables(conn_superhuman)

Schema for table 'superhuman':
  rsid (TEXT)
  gene (TEXT)
  polymorphism (TEXT)
  location_38 (TEXT)
  ref_allele (TEXT)
  alt_allele (TEXT)
  genotype (TEXT)
  zygosity (TEXT)
  superability (TEXT)
  adverse_effects (TEXT)
  references (TEXT)

[('superhuman',)]

In [55]:
#superhuman = pl.read_database("SELECT * FROM superhuman", connection=conn_superhuman).lazy()

superhuman = pl.read_database(
    "SELECT * FROM superhuman", 
    connection=conn_superhuman,
    infer_schema_length=None 
).lazy()

superhuman.head(5).collect(engine="streaming")

shape: (5, 11)
┌──────────────┬───────┬──────────────┬─────────────┬────────────┬────────────┬──────────┬──────────┬─────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────────────────────┐
│ rsid         ┆ gene  ┆ polymorphism ┆ location_38 ┆ ref_allele ┆ alt_allele ┆ genotype ┆ zygosity ┆ superability                            ┆ adverse_effects                             ┆ references                                    │
│ ---          ┆ ---   ┆ ---          ┆ ---         ┆ ---        ┆ ---        ┆ ---      ┆ ---      ┆ ---                                     ┆ ---                                         ┆ ---                                           │
│ str          ┆ str   ┆ str          ┆ str         ┆ str        ┆ str        ┆ str      ┆ str      ┆ str                                     ┆ str                                         ┆ str                                           │
╞══════════════╪═══════╪══════════════╪═════════════╪════════════╪════════════╪══════════╪══════════╪═════════════════════════════════════════╪═════════════════════════════════════════════╪═══════════════════════════════════════════════╡
│ rs1007211    ┆ NTRK1 ┆ null         ┆ 1:156860987 ┆ G          ┆ A          ┆ null     ┆ hom      ┆ Pain insensitive, no sweat (anhydrosis) ┆ Unnoticed harm, hyperthermia                ┆ https://www.ncbi.nlm.nih.gov/snp/rs1007211    │
│ rs1009726086 ┆ NTRK1 ┆ null         ┆ 1:156881499 ┆ C          ┆ T          ┆ null     ┆ hom      ┆ Pain insensitive, no sweat (anhydrosis) ┆ Unnoticed harm, hyperthermia                ┆ https://www.ncbi.nlm.nih.gov/snp/rs1009726086 │
│ rs1012788466 ┆ RIMS1 ┆ null         ┆ 6:72217222  ┆ C          ┆ A          ┆ null     ┆ hom      ┆ High cognitive                          ┆ Late onset visual loss (Cone-rod dystrophy) ┆ https://www.ncbi.nlm.nih.gov/snp/rs1012788466 │
│ rs1012788466 ┆ RIMS1 ┆ null         ┆ 6:72217222  ┆ C          ┆ T          ┆ null     ┆ hom      ┆ High cognitive                          ┆ Late onset visual loss (Cone-rod dystrophy) ┆ https://www.ncbi.nlm.nih.gov/snp/rs1012788466 │
│ rs1015184575 ┆ SCN9A ┆ null         ┆ 2:166195470 ┆ A          ┆ G          ┆ null     ┆ hom      ┆ Pain insensitive                        ┆ Same variants may cause hypersensitivity    ┆ https://www.ncbi.nlm.nih.gov/snp/rs1015184575 │
└──────────────┴───────┴──────────────┴─────────────┴────────────┴────────────┴──────────┴──────────┴─────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────────────────────┘

# VOMax

In [50]:
vo2max_db = modules / "just_vo2max" / "vo2max.sqlite"
conn_vo2max = sqlite3.connect(vo2max_db)
print_tables(conn_vo2max)

Schema for table 'genotype_weights':
  index (INTEGER)
  rsID (TEXT)
  genotype (TEXT)
  weight (TEXT)
  genotype_specific_conclusion (TEXT)
  ref_allele (TEXT)
  alt_allele (TEXT)
  risk_allele (TEXT)
  allele (TEXT)
  state (TEXT)
  zygosity (TEXT)

Schema for table 'rsid':
  index (INTEGER)
  rsid (TEXT)
  gene (TEXT)
  ref_allele (TEXT)
  alt_allele (TEXT)
  risk_allele (TEXT)
  rsid_conclusion (TEXT)
  pmids (TEXT)
  population (TEXT)
  p_value (TEXT)

[('genotype_weights',), ('rsid',)]

In [53]:
vo2max_rsids = pl.read_database("SELECT * FROM rsid", connection=conn_vo2max).lazy()
vo2max_rsids.head(5).collect(engine="streaming")

shape: (5, 10)
┌───────┬────────────┬──────────┬────────────┬────────────┬─────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────┬─────────────────────────────┬─────────────────┐
│ index ┆ rsid       ┆ gene     ┆ ref_allele ┆ alt_allele ┆ risk_allele ┆ rsid_conclusion                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ┆ pmids                             ┆ population                  ┆ p_value         │
│ ---   ┆ ---        ┆ ---      ┆ ---        ┆ ---        ┆ ---         ┆ ---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ┆ ---                               ┆ ---                         ┆ ---             │
│ i64   ┆ str        ┆ str      ┆ str        ┆ str        ┆ str         ┆ str                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ┆ str                               ┆ str                         ┆ str             │
╞═══════╪════════════╪══════════╪════════════╪════════════╪═════════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════════════════════════════╪═════════════════════════════╪═════════════════╡
│ 0     ┆ rs17602729 ┆ AMPD1    ┆ G          ┆ A          ┆ A           ┆ The AMPD1 gene encodes the enzyme adenosine monophosphate deaminase, which is one of the key enzymes used to process the energy source ATP. The C34T variation causes a premature stop in the protein, leading to a nonfunctional AMPD1 enzyme. Some individuals - but by no means all or even a majority apparently - who are AMPD1 deficient get muscle cramps and pains when they exert themselves. Association with Vo2 max responce was shown in 2 studies.                                                                                                                                                            ┆ [PMID 21967077]; [PMID 2783984]   ┆
 Caucasian                ┆ 0.04            │
│ 1     ┆ rs884736   ┆ CAMTA1   ┆ T          ┆ A          ┆ A           ┆ The CAMTA1 gene encodes a protein that belongs to the calmodulin-binding transcription activator (CAMTA) family. This protein is involved in various cellular processes. It has been associated with the development and function of brain, heart, and skeletal muscles. In the context of sports performance and VO2 max, the exact function of the CAMTA1 gene is not fully elucidated. It's believed to play a role in physiological adaptations to exercise and might influence factors such as muscle endurance, oxygen utilization, and energy metabolism.  Association with Vo2 max responce was shown in 2 studies. ┆ [PMID 21183627]; [PMID: 23990238] ┆ Caucasian;African-American  ┆ 1.49E-4         │
│ 2     ┆ rs10921078 ┆ RGS18    ┆ G          ┆ A          ┆ G           ┆ The RGS18 gene codes for a protein, which is part of a group that helps regulate cellular signaling pathways. In the context of sports performance and VO2 max, the RGS18 gene might influence how the body responds to certain signals during exercise. It's thought to play a role in processes like muscle contraction, blood flow regulation, and energy utilization. However, the exact details of how variations in the RGS18 gene impact these factors and contribute to athletic performance are still being investigated by scientists. Association with Vo2 max responce was shown in 2 studies.                  ┆ [PMID 21183627]                   ┆ Caucasian; African-American ┆ 7.17E-5         │
│ 3     ┆ rs11715829 ┆ ZIC4     ┆ T          ┆ C          ┆ T           ┆ The ZIC4 gene encodes a protein involved in the development and function of the nervous system, especially during embryonic development. It plays a role in regulating the expression of other genes that are crucial for proper neural development. In relation to sports performance and VO2 max, the exact function of the ZIC4 gene is not well understood. However, genes related to neural development can indirectly influence athletic abilities by affecting factors like coordination, motor control, and muscle response. Association with Vo2 max responce was shown in 2 studies.                              ┆ [PMID 21183627]                   ┆
 Caucasian                ┆ 8.68E−6         │
│ 4     ┆ rs4952535  ┆ FLJ44450 ┆ G          ┆ A          ┆ A           ┆ The association with V̇o2max training responses with P < 1.5 × 10−4 was shown in HERITAGE study.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ┆ [PMID 21183627]                   ┆ Caucasian                   ┆ 1.01E-4         │
└───────┴────────────┴──────────┴────────────┴────────────┴─────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────┴─────────────────────────────┴─────────────────┘

In [54]:
vo2max_rsids = pl.read_database("SELECT * FROM genotype_weights", connection=conn_vo2max).lazy()
vo2max_rsids.head(5).collect(engine="streaming")

shape: (5, 11)
┌───────┬────────────┬──────────┬────────┬─────────────────────────────────┬────────────┬────────────┬─────────────┬────────┬───────┬──────────┐
│ index ┆ rsID       ┆ genotype ┆ weight ┆ genotype_specific_conclusion    ┆ ref_allele ┆ alt_allele ┆ risk_allele ┆ allele ┆ state ┆ zygosity │
│ ---   ┆ ---        ┆ ---      ┆ ---    ┆ ---                             ┆ ---        ┆ ---        ┆ ---         ┆ ---    ┆ ---   ┆ ---      │
│ i64   ┆ str        ┆ str      ┆ str    ┆ str                             ┆ str        ┆ str        ┆ str         ┆ str    ┆ str   ┆ str      │
╞═══════╪════════════╪══════════╪════════╪═════════════════════════════════╪════════════╪════════════╪═════════════╪════════╪═══════╪══════════╡
│ 0     ┆ rs17602729 ┆ GG       ┆ 0      ┆ Normal VO2max training response ┆ G          ┆ A          ┆ A           ┆ G      ┆ ref   ┆ hom      │
│ 1     ┆ rs17602729 ┆ GA       ┆ -0.5   ┆ Low VO2max training response    ┆ G          ┆ A          ┆ A           ┆ A      ┆ alt   ┆ het      │
│ 2     ┆ rs17602729 ┆ AA       ┆ -1     ┆ Low VO2max training response    ┆ G          ┆ A          ┆ A           ┆ A      ┆ alt   ┆ hom      │
│ 3     ┆ rs884736   ┆ TT       ┆ 0      ┆ Normal VO2max training response ┆ T          ┆ A          ┆ A           ┆ T      ┆ ref   ┆ hom      │
│ 4     ┆ rs884736   ┆ TA       ┆ 0      ┆ Normal VO2max training response ┆ T          ┆ A          ┆ A           ┆ A      ┆ alt   ┆ het      │
└───────┴────────────┴──────────┴────────┴─────────────────────────────────┴────────────┴────────────┴─────────────┴────────┴───────┴──────────┘

# Filtered Modules

In [47]:
cancer_genes_path = modules / "just_cancer" / "genes.txt"
if cancer_genes_path.exists():
    cancer_genes = pl.read_csv(cancer_genes_path, has_header=False, new_columns=["gene_symbol"]).lazy()
    print("Cancer genes sample:")
    print(cancer_genes.head(5).collect())

Cancer genes sample:
shape: (5, 1)
┌─────────────┐
│ gene_symbol │
│ ---         │
│ str         │
╞═════════════╡
│ ABL1        │
│ CRLF2       │
│ GATA1       │
│ MTOR        │
│ RHBDF2      │
└─────────────┘

# Drugs

In [48]:
drugs_path = modules / "just_drugs" / "annotation_tab.tsv"
if drugs_path.exists():
    drugs_annotations = pl.read_csv(drugs_path, separator="\t").lazy()
    print("Drugs annotations sample:")
    print(drugs_annotations.head(5).collect())

Drugs annotations sample:
shape: (5, 13)
┌───────────────────────┬────────────────────┬─────────────┬────────────────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────┬─────────────────────────────────┬─────────┬─────────────────┬────────────┬───────────────────────────┬──────────────────────────┐
│ Variant Annotation ID ┆ Variant/Haplotypes ┆ Drug(s)     ┆ Phenotype Category ┆ Significance ┆ Sentence                                                                                                       ┆ Allele Of Frequency In Cases ┆ Allele Of Frequency In Controls ┆ P Value ┆ Ratio Stat Type ┆ Ratio Stat ┆ Confidence Interval Start ┆ Confidence Interval Stop │
│ ---                   ┆ ---                ┆ ---         ┆ ---                ┆ ---          ┆ ---                                                                                                            ┆ ---                          ┆ ---                             ┆ ---     ┆ ---             ┆ ---        ┆ ---                       ┆ ---                      │
│ i64                   ┆ str                ┆ str         ┆ str                ┆ str          ┆ str                                                                                                            ┆ str                          ┆ str                             ┆ str     ┆ str             ┆ f64        ┆ f64                       ┆ f64                      │
╞═══════════════════════╪════════════════════╪═════════════╪════════════════════╪══════════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════════════════════╪═════════════════════════════════╪═════════╪═════════════════╪════════════╪═══════════════════════════╪══════════════════════════╡
│ 1451307925            ┆ rs9839376          ┆ ritodrine   ┆ Efficacy           ┆ yes          ┆ Genotype CC is associated with decreased response to ritodrine as compared to genotypes CT + TT.               ┆ null                         ┆ null                            ┆ < 0.05  ┆ HR              ┆ 2.68       ┆ 1.16                      ┆ 6.2                      │
│ 1451307920            ┆ rs7624046          ┆ ritodrine   ┆ Efficacy           ┆ yes          ┆ Genotype TT is associated with decreased response to ritodrine as compared to genotypes CC + CT.               ┆ null                         ┆ null                            ┆ < 0.05  ┆ HR              ┆ 2.06       ┆ 1.14                      ┆ 3.73                     │
│ 1451339660            ┆ rs10011796         ┆ allopurinol ┆ Efficacy           ┆ no           ┆ Allele T is not associated with decreased response to allopurinol in people with Gout as compared to allele C. ┆ T                            ┆ T                               ┆ = 0.017 ┆ OR              ┆ 1.55       ┆ 1.08                      ┆ 2.23                     │
│ 1451339660            ┆ rs10011796         ┆ allopurinol ┆ Efficacy           ┆ no           ┆ Allele T is not associated with decreased response to allopurinol in people with Gout as compared to allele C. ┆ T                            ┆ T                               ┆ = 0.59  ┆ OR              ┆ 1.12       ┆ 0.73                      ┆ 1.73                     │
│ 1451339660            ┆ rs10011796         ┆ allopurinol ┆ Efficacy           ┆ no           ┆ Allele T is not associated with decreased response to allopurinol in people with Gout as compared to allele C. ┆ null                         ┆ null                            ┆ = 0.689 ┆ OR              ┆ 1.063      ┆ 0.789                     ┆ 1.431                    │
└───────────────────────┴────────────────────┴─────────────┴────────────────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────┴─────────────────────────────────┴─────────┴─────────────────┴────────────┴───────────────────────────┴──────────────────────────┘

# PRS

In [56]:
prs_db = modules / "just_prs" / "prs.sqlite"
conn_prs = sqlite3.connect(prs_db)

In [57]:
print_tables(conn_prs)

Schema for table 'weights':
  id (INTEGER)
  rsid (TEXT)
  chrom (TEXT)
  pos (INTEGER)
  other_allele (TEXT)
  effect_allele (TEXT)
  ref (TEXT)
  weight (REAL)
  prsid (INTEGER)

Schema for table 'prs':
  id (INTEGER)
  title (TEXT)
  name (TEXT)
  total (INTEGER)
  invers (INTEGER)

Schema for table 'percentiles':
  id (INTEGER)
  value (float)
  percent (float)
  prs_id (INTEGER)

[('weights',), ('prs',), ('percentiles',)]

In [58]:
prs = pl.read_database("SELECT * FROM prs", connection=conn_prs).lazy()
prs.head(5).collect(engine="streaming")

shape: (5, 5)
┌─────┬────────────────────────────────────┬───────────┬───────┬────────┐
│ id  ┆ title                              ┆ name      ┆ total ┆ invers │
│ --- ┆ ---                                ┆ ---       ┆ ---   ┆ ---    │
│ i64 ┆ str                                ┆ str       ┆ i64   ┆ i64    │
╞═════╪════════════════════════════════════╪═══════════╪═══════╪════════╡
│ 1   ┆ Longevity PRS                      ┆ PRS5      ┆ 330   ┆ 1      │
│ 2   ┆ Blood clot or deep vein thrombosis ┆ PGS000931 ┆ 534   ┆ 0      │
│ 3   ┆ Coronary heart disease             ┆ PGS000818 ┆ 138   ┆ 0      │
│ 4   ┆ Coronary atherosclerosis           ┆ PGS001839 ┆ 25425 ┆ 0      │
│ 5   ┆ C-reactive protein measurement     ┆ PGS000314 ┆ 77    ┆ 0      │
└─────┴────────────────────────────────────┴───────────┴───────┴────────┘

In [59]:
prs_weights = pl.read_database("SELECT * FROM weights", connection=conn_prs).lazy()
prs_weights.head(5).collect(engine="streaming")

shape: (5, 9)
┌─────┬────────────┬───────┬───────────┬──────────────┬───────────────┬─────┬───────────┬───────┐
│ id  ┆ rsid       ┆ chrom ┆ pos       ┆ other_allele ┆ effect_allele ┆ ref ┆ weight    ┆ prsid │
│ --- ┆ ---        ┆ ---   ┆ ---       ┆ ---          ┆ ---           ┆ --- ┆ ---       ┆ ---   │
│ i64 ┆ str        ┆ str   ┆ i64       ┆ str          ┆ str           ┆ str ┆ f64       ┆ i64   │
╞═════╪════════════╪═══════╪═══════════╪══════════════╪═══════════════╪═════╪═══════════╪═══════╡
│ 1   ┆ rs12413812 ┆ chr10 ┆ 100140109 ┆ G            ┆ A             ┆ A   ┆ -0.016524 ┆ 1     │
│ 2   ┆ rs7901883  ┆ chr10 ┆ 101427081 ┆ G            ┆ A             ┆ G   ┆ 0.019525  ┆ 1     │
│ 3   ┆ rs7912503  ┆ chr10 ┆ 101915653 ┆ T            ┆ A             ┆ T   ┆ 0.020503  ┆ 1     │
│ 4   ┆ rs11191816 ┆ chr10 ┆ 103824401 ┆ G            ┆ A             ┆ G   ┆ 0.019594  ┆ 1     │
│ 5   ┆ rs2286629  ┆ chr10 ┆ 117542183 ┆ G            ┆ T             ┆ T   ┆ 0.02445   ┆ 1     │
└─────┴────────────┴───────┴───────────┴──────────────┴───────────────┴─────┴───────────┴───────┘

In [60]:
prs_percentiles = pl.read_database("SELECT * FROM percentiles", connection=conn_prs).lazy()
prs_percentiles.head(5).collect(engine="streaming")

shape: (5, 4)
┌─────┬───────────┬─────────┬────────┐
│ id  ┆ value     ┆ percent ┆ prs_id │
│ --- ┆ ---       ┆ ---     ┆ ---    │
│ i64 ┆ f64       ┆ f64     ┆ i64    │
╞═════╪═══════════╪═════════╪════════╡
│ 1   ┆ -0.229987 ┆ 0.01    ┆ 1      │
│ 2   ┆ -0.166865 ┆ 0.02    ┆ 1      │
│ 3   ┆ -0.126816 ┆ 0.03    ┆ 1      │
│ 4   ┆ -0.096689 ┆ 0.04    ┆ 1      │
│ 5   ┆ -0.072183 ┆ 0.05    ┆ 1      │
└─────┴───────────┴─────────┴────────┘

In [63]:
import polars_bio as pb
borysova_path = "/home/antonkulaga/data/genomes/Borysova/BorysovaGenome.vcf"
borysova = pb.scan_vcf(borysova_path)
borysova.head(5).collect(engine="streaming")

5rows [00:00, 45.67rows/s]

shape: (5, 31)
┌───────┬───────┬───────┬─────────────┬─────┬───────┬────────────┬────────┬───────────┬───────────┬─────┬──────────────┬──────┬─────┬──────┬───────────┬─────┬────────────────┬─────────────────┬───────────┬───────────┬──────┬───────────┬─────────────────────┬─────────────────────┬───────┬─────────────┬────────────────┬───────┬────────┬─────────┐
│ chrom ┆ start ┆ end   ┆ id          ┆ ref ┆ alt   ┆ qual       ┆ filter ┆ AC        ┆ AF        ┆ AN  ┆ BaseQRankSum ┆ DB   ┆ DP  ┆ END  ┆ ExcessHet ┆ FS  ┆ HaplotypeScore ┆ InbreedingCoeff ┆ MLEAC     ┆ MLEAF     ┆ MQ   ┆ MQRankSum ┆ NEGATIVE_TRAIN_SITE ┆ POSITIVE_TRAIN_SITE ┆ QD    ┆ RAW_MQandDP ┆ ReadPosRankSum ┆ SOR   ┆ VQSLOD ┆ culprit │
│ ---   ┆ ---   ┆ ---   ┆ ---         ┆ --- ┆ ---   ┆ ---        ┆ ---    ┆ ---       ┆ ---       ┆ --- ┆ ---          ┆ ---  ┆ --- ┆ ---  ┆ ---       ┆ --- ┆ ---            ┆ ---             ┆ ---       ┆ ---       ┆ ---  ┆ ---       ┆ ---                 ┆ ---                 ┆ ---   ┆ ---         ┆ ---            ┆ ---   ┆ ---    ┆ ---     │
│ str   ┆ u32   ┆ u32   ┆ str         ┆ str ┆ str   ┆ f64        ┆ str    ┆ list[i32] ┆ list[f32] ┆ i32 ┆ f32          ┆ bool ┆ i32 ┆ i32  ┆ f32       ┆ f32 ┆ f32            ┆ f32             ┆ list[i32] ┆ list[f32] ┆ f32  ┆ f32       ┆ bool                ┆ bool                ┆ f32   ┆ list[i32]   ┆ f32            ┆ f32   ┆ f32    ┆ str     │
╞═══════╪═══════╪═══════╪═════════════╪═════╪═══════╪════════════╪════════╪═══════════╪═══════════╪═════╪══════════════╪══════╪═════╪══════╪═══════════╪═════╪════════════════╪═════════════════╪═══════════╪═══════════╪══════╪═══════════╪═════════════════════╪═════════════════════╪═══════╪═════════════╪════════════════╪═══════╪════════╪═════════╡
│ chr1  ┆ 10904 ┆ 10904 ┆ rs10218493  ┆ G   ┆ A     ┆ 216.770004 ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ 3.48         ┆ true ┆ 19  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ -0.396    ┆ false               ┆ false               ┆ 11.41 ┆ null        ┆ -1.184         ┆ 0.321 ┆ 1.83   ┆ FS      │
│ chr1  ┆ 10927 ┆ 10927 ┆ rs10218527  ┆ A   ┆ G     ┆ 145.770004 ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ 2.74         ┆ true ┆ 17  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ 0.775     ┆ false               ┆ false               ┆ 8.57  ┆ null        ┆ -0.057         ┆ 0.193 ┆ 0.55   ┆ QD      │
│ chr1  ┆ 12807 ┆ 12807 ┆ rs62635285  ┆ C   ┆ T     ┆ 53.77      ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ 1.17         ┆ true ┆ 11  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ -2.509    ┆ false               ┆ false               ┆ 4.89  ┆ null        ┆ 0.361          ┆ 0.33  ┆ 0.616  ┆ QD      │
│ chr1  ┆ 13273 ┆ 13273 ┆ rs531730856 ┆ G   ┆ C     ┆ 1050.77002 ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ -0.674       ┆ true ┆ 51  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ 0.625     ┆ false               ┆ false               ┆ 21.02 ┆ null        ┆ -0.864         ┆ 0.587 ┆ 2.94   ┆ FS      │
│ chr1  ┆ 13417 ┆ 13417 ┆ rs777038595 ┆ C   ┆ CGAGA ┆ 1176.72998 ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ 0.153        ┆ true ┆ 47  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ -0.129    ┆ false               ┆ false               ┆ 26.74 ┆ null        ┆ 1.51           ┆ 0.693 ┆ 3.7    ┆ QD      │
└───────┴───────┴───────┴─────────────┴─────┴───────┴────────────┴────────┴───────────┴───────────┴─────┴──────────────┴──────┴─────┴──────┴───────────┴─────┴────────────────┴─────────────────┴───────────┴───────────┴──────┴───────────┴─────────────────────┴─────────────────────┴───────┴─────────────┴────────────────┴───────┴────────┴─────────┘

In [65]:
antonkulaga_path = "/home/antonkulaga/data/genomes/Anton/antonkulaga.parquet"
antonkulaga = pl.scan_parquet(antonkulaga_path)
antonkulaga.head(5).collect(engine="streaming")
antonkulaga.columns

/tmp/ipykernel_16798/2237829397.py:4: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  antonkulaga.columns

['chrom', 'start', 'end', 'id', 'ref', 'alt', 'qual', 'filter', 'END']

In [66]:
antonkulaga_path = "/home/antonkulaga/data/genomes/Anton/antonkulaga.vcf"
antonkulaga = pb.scan_vcf(antonkulaga_path)
antonkulaga.head(5).collect(engine="streaming")
antonkulaga.columns

5rows [00:00, 237.88rows/s]
/tmp/ipykernel_16798/3883504551.py:4: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  antonkulaga.columns

['chrom', 'start', 'end', 'id', 'ref', 'alt', 'qual', 'filter', 'END']

In [67]:
antonkulaga.head(5).collect(engine="streaming")

5rows [00:00, 263.39rows/s]

shape: (5, 9)
┌───────┬───────┬───────┬─────┬─────┬─────┬──────┬─────────┬──────┐
│ chrom ┆ start ┆ end   ┆ id  ┆ ref ┆ alt ┆ qual ┆ filter  ┆ END  │
│ ---   ┆ ---   ┆ ---   ┆ --- ┆ --- ┆ --- ┆ ---  ┆ ---     ┆ ---  │
│ str   ┆ u32   ┆ u32   ┆ str ┆ str ┆ str ┆ f64  ┆ str     ┆ i32  │
╞═══════╪═══════╪═══════╪═════╪═════╪═════╪══════╪═════════╪══════╡
│ 1     ┆ 10009 ┆ 10009 ┆     ┆ A   ┆ AC  ┆ 0.0  ┆ RefCall ┆ null │
│ 1     ┆ 10015 ┆ 10015 ┆     ┆ A   ┆ G   ┆ 0.0  ┆ RefCall ┆ null │
│ 1     ┆ 10021 ┆ 10021 ┆     ┆ A   ┆ G   ┆ 0.0  ┆ RefCall ┆ null │
│ 1     ┆ 10027 ┆ 10027 ┆     ┆ A   ┆ G   ┆ 0.0  ┆ RefCall ┆ null │
│ 1     ┆ 10033 ┆ 10033 ┆     ┆ A   ┆ G   ┆ 0.0  ┆ RefCall ┆ null │
└───────┴───────┴───────┴─────┴─────┴─────┴──────┴─────────┴──────┘

In [64]:
borysova.columns

/tmp/ipykernel_16798/3668106042.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  borysova.columns

['chrom',
 'start',
 'end',
 'id',
 'ref',
 'alt',
 'qual',
 'filter',
 'AC',
 'AF',
 'AN',
 'BaseQRankSum',
 'DB',
 'DP',
 'END',
 'ExcessHet',
 'FS',
 'HaplotypeScore',
 'InbreedingCoeff',
 'MLEAC',
 'MLEAF',
 'MQ',
 'MQRankSum',
 'NEGATIVE_TRAIN_SITE',
 'POSITIVE_TRAIN_SITE',
 'QD',
 'RAW_MQandDP',
 'ReadPosRankSum',
 'SOR',
 'VQSLOD',
 'culprit']

In [68]:
borysova.head(5).collect(engine="streaming")

5rows [00:00, 46.05rows/s]

shape: (5, 31)
┌───────┬───────┬───────┬─────────────┬─────┬───────┬────────────┬────────┬───────────┬───────────┬─────┬──────────────┬──────┬─────┬──────┬───────────┬─────┬────────────────┬─────────────────┬───────────┬───────────┬──────┬───────────┬─────────────────────┬─────────────────────┬───────┬─────────────┬────────────────┬───────┬────────┬─────────┐
│ chrom ┆ start ┆ end   ┆ id          ┆ ref ┆ alt   ┆ qual       ┆ filter ┆ AC        ┆ AF        ┆ AN  ┆ BaseQRankSum ┆ DB   ┆ DP  ┆ END  ┆ ExcessHet ┆ FS  ┆ HaplotypeScore ┆ InbreedingCoeff ┆ MLEAC     ┆ MLEAF     ┆ MQ   ┆ MQRankSum ┆ NEGATIVE_TRAIN_SITE ┆ POSITIVE_TRAIN_SITE ┆ QD    ┆ RAW_MQandDP ┆ ReadPosRankSum ┆ SOR   ┆ VQSLOD ┆ culprit │
│ ---   ┆ ---   ┆ ---   ┆ ---         ┆ --- ┆ ---   ┆ ---        ┆ ---    ┆ ---       ┆ ---       ┆ --- ┆ ---          ┆ ---  ┆ --- ┆ ---  ┆ ---       ┆ --- ┆ ---            ┆ ---             ┆ ---       ┆ ---       ┆ ---  ┆ ---       ┆ ---                 ┆ ---                 ┆ ---   ┆ ---         ┆ ---            ┆ ---   ┆ ---    ┆ ---     │
│ str   ┆ u32   ┆ u32   ┆ str         ┆ str ┆ str   ┆ f64        ┆ str    ┆ list[i32] ┆ list[f32] ┆ i32 ┆ f32          ┆ bool ┆ i32 ┆ i32  ┆ f32       ┆ f32 ┆ f32            ┆ f32             ┆ list[i32] ┆ list[f32] ┆ f32  ┆ f32       ┆ bool                ┆ bool                ┆ f32   ┆ list[i32]   ┆ f32            ┆ f32   ┆ f32    ┆ str     │
╞═══════╪═══════╪═══════╪═════════════╪═════╪═══════╪════════════╪════════╪═══════════╪═══════════╪═════╪══════════════╪══════╪═════╪══════╪═══════════╪═════╪════════════════╪═════════════════╪═══════════╪═══════════╪══════╪═══════════╪═════════════════════╪═════════════════════╪═══════╪═════════════╪════════════════╪═══════╪════════╪═════════╡
│ chr1  ┆ 10904 ┆ 10904 ┆ rs10218493  ┆ G   ┆ A     ┆ 216.770004 ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ 3.48         ┆ true ┆ 19  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ -0.396    ┆ false               ┆ false               ┆ 11.41 ┆ null        ┆ -1.184         ┆ 0.321 ┆ 1.83   ┆ FS      │
│ chr1  ┆ 10927 ┆ 10927 ┆ rs10218527  ┆ A   ┆ G     ┆ 145.770004 ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ 2.74         ┆ true ┆ 17  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ 0.775     ┆ false               ┆ false               ┆ 8.57  ┆ null        ┆ -0.057         ┆ 0.193 ┆ 0.55   ┆ QD      │
│ chr1  ┆ 12807 ┆ 12807 ┆ rs62635285  ┆ C   ┆ T     ┆ 53.77      ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ 1.17         ┆ true ┆ 11  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ -2.509    ┆ false               ┆ false               ┆ 4.89  ┆ null        ┆ 0.361          ┆ 0.33  ┆ 0.616  ┆ QD      │
│ chr1  ┆ 13273 ┆ 13273 ┆ rs531730856 ┆ G   ┆ C     ┆ 1050.77002 ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ -0.674       ┆ true ┆ 51  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ 0.625     ┆ false               ┆ false               ┆ 21.02 ┆ null        ┆ -0.864         ┆ 0.587 ┆ 2.94   ┆ FS      │
│ chr1  ┆ 13417 ┆ 13417 ┆ rs777038595 ┆ C   ┆ CGAGA ┆ 1176.72998 ┆ PASS   ┆ [1]       ┆ [0.5]     ┆ 2   ┆ 0.153        ┆ true ┆ 47  ┆ null ┆ 3.0103    ┆ 0.0 ┆ null           ┆ null            ┆ [1]       ┆ [0.5]     ┆ null ┆ -0.129    ┆ false               ┆ false               ┆ 26.74 ┆ null        ┆ 1.51           ┆ 0.693 ┆ 3.7    ┆ QD      │
└───────┴───────┴───────┴─────────────┴─────┴───────┴────────────┴────────┴───────────┴───────────┴─────┴──────────────┴──────┴─────┴──────┴───────────┴─────┴────────────────┴─────────────────┴───────────┴───────────┴──────┴───────────┴─────────────────────┴─────────────────────┴───────┴─────────────┴────────────────┴───────┴────────┴─────────┘